// Agent Card data for Supaprod's A2A presence.
// Pure functions — no DB. Shared between the card route AND the server.ts
// well-known handler so the two representations never drift.

export const AGENT_CARD_VERSION = "0.8.0";
export const AGENT_CARD_SCHEMA_VERSION = "0.1";

export function buildAgentCard(origin: string): Record<string, unknown> {
  return {
    schema_version: AGENT_CARD_SCHEMA_VERSION,
    name: "Supaprod",
    slug: "supaprod",
    version: AGENT_CARD_VERSION,
    // THE DESCRIPTION IS POSITIONING, not a feature list, because this is the
    // first and often the only thing an agent or answer engine reads about us.
    // It used to say every artifact "lives in one place", which is the storage
    // claim README.md bans of the brain: any vendor can hold your decisions, and
    // describing us as the place they sit gives away the argument and claims
    // less than the product delivers. It also listed six departments and never
    // reached the verb that compounds.
    /**
     * THE OPENING CLAUSE IS THE CATEGORY, AND IT CHANGED ON 2026-08-11 BY
     * FOUNDER RULING. It read "The agentic-first operating system for product
     * teams", which was retired as the lead on 2026-08-10 and retired
     * EVERYWHERE the following day, machine-readable surfaces included.
     *
     * The exception this card might have claimed is the reason it does not get
     * one. An answer engine genuinely does want a precise categorical
     * definition, so the instinct is that a machine surface should keep the
     * crispest phrase available. But a machine surface is the one place a
     * sentence propagates WITHOUT a human choosing to repeat it: an LLM asked
     * "what is Supaprod" reads this and answers with it, at scale, forever. The
     * phrase the founder finds vague is the last one that should be handed to
     * the surface that repeats itself.
     *
     * The replacement is the approved sub-50-word opener and is still
     * CATEGORICAL, which is what this card needs. It just is not a platform
     * word.
     */
    description:
      "Supaprod is where product decisions live when agents do the work. Supaprod tells you what to build, builds it, ships it, checks what actually happened, and learns from it, so next time it guides the call. Seven stations (Discover, Decide, Plan, Design, Build, Ship, Learn) that agents walk on their own inside boundaries a human sets in advance. A settled outcome is written back against the decision that caused it and re-ranks what surfaces next, which is the part that compounds. Nothing merges, ships, or takes an irreversible outward action without a human approval.",
    provider: { organization: "Supaprod", url: origin },
    documentation_url: `${origin}/integrations`,
    discovery_url: `${origin}/.well-known/agent.json`,
    // `/api/mcp`, and this REVERSES the 2026-08-07 change, which was wrong.
    //
    // That change moved the card to `/mcp` on the strength of a GET probe, and
    // its stated reason ("there is no /api/mcp route file anywhere in
    // src/routes/") is false: src/routes/api/mcp.ts exists and is this
    // product's MCP server. The GET probe misled because GET on an API route
    // falls through to the SPA shell; the method that matters is POST.
    //
    // Measured live 2026-08-10, POST with a JSON-RPC body:
    //
    //   POST /api/mcp  -> {"jsonrpc":"2.0","error":{"code":-32003,
    //                      "message":"Missing bearer token"},"id":1}
    //   POST /mcp      -> {"error":"unauthorized"}        (not JSON-RPC shaped)
    //
    // The two paths are DIFFERENT SERVERS, which is the part the earlier fix
    // missed. src/routes/mcp.ts is auto-generated by @lovable.dev/mcp-js and
    // serves four tools (list_decisions, list_workspaces, search_signals,
    // whoami). The ten read tools listed below live in src/routes/api/mcp.ts.
    // Only `search_signals` exists in both.
    //
    // So the card was advertising ten tools at an endpoint serving one of them,
    // and an agent calling get_ard or search_decisions got "tool not found".
    // This card is the one artifact whose entire job is being followed by a
    // machine, which is exactly why the endpoint has to match the catalogue.
    endpoints: {
      message_send: `${origin}/api/public/a2a/message/send`,
      message_stream: `${origin}/api/public/a2a/message/stream`,
      tasks: `${origin}/api/public/a2a/tasks`,
      mcp: `${origin}/api/mcp`,
    },
    mcp: {
      endpoint: `${origin}/api/mcp`,
      protocol_versions: ["2025-06-18", "2025-03-26", "2024-11-05"],
      transport: "http+json-rpc-2.0",
      authentication: "bearer",
      token_issuance: `${origin}/settings?section=interop`,
      read_tools: [
        "search_signals",
        "search_opportunities",
        "search_decisions",
        "search_prds",
        "get_prd",
        "get_ard",
        "get_roadmap",
        "export_skillpack",
        "get_governing_decision",
        "get_contradiction_history",
      ],
      write_tools: [{ name: "ingest_signal", required_scope: "write:signal" }],
      rate_limit_per_minute: 60,
    },
    agents_txt: `${origin}/agents.txt`,
    rate_limits: {
      requests_per_minute: 60,
      burst_per_second: 10,
      exceeded_code: -32002,
    },
    content_tiers: {
      decisions: "read",
      signals: "read+write:signal",
      opportunities: "read",
      specs: "read",
      knowledge: "read",
    },
    write_scopes_available: ["write:signal"],
    authentication: {
      schemes: ["bearer"],
      token_url: `${origin}/integrations`,
      protected_resource_metadata: `${origin}/.well-known/oauth-protected-resource`,
    },
    capabilities: {
      streaming: true,
      push_notifications: false,
      multi_turn: false,
      file_attachments: false,
    },
    default_input_modes: ["text/plain", "application/json"],
    default_output_modes: ["application/json"],
    skills: [
      {
        id: "discovery.search_signals",
        name: "Search discovery signals",
        description:
          "Search across user feedback, sales notes, support tickets, and meeting transcripts. Pass the topic or keyword as message text; returns up to 20 ranked signals.",
        input_modes: ["text/plain"],
        output_modes: ["application/json"],
        tags: ["discovery", "read"],
      },
      {
        id: "knowledge.export_skillpack",
        name: "Export decision skill-pack",
        description:
          "Export the workspace's distilled, citable lessons as a versioned, content-hashed bundle. A peer agent can load this as context before making decisions.",
        input_modes: ["text/plain"],
        output_modes: ["application/json"],
        tags: ["knowledge", "memory", "read"],
      },
      {
        id: "discovery.ingest_signal",
        name: "Contribute a discovery signal",
        description:
          "Submit a product signal into the workspace. Requires a token carrying the write:signal scope AND the workspace's outward-write gate enabled. Text is injection-screened before storage.",
        input_modes: ["application/json"],
        output_modes: ["application/json"],
        tags: ["discovery", "write", "scoped"],
      },
    ],
    policies: {
      destructive_actions_require_approval: true,
      pii_egress_filtered: true,
      rate_limit_per_minute: 60,
      writes_require_scope_and_gate: true,
    },
  };
}

export function buildOAuthProtectedResourceMetadata(origin: string): Record<string, unknown> {
  return {
    resource: origin,
    authorization_servers: [],
    bearer_methods_supported: ["header"],
    scopes_supported: ["read", "write:signal"],
    token_endpoint_auth_methods_supported: ["none"],
    documentation_url: `${origin}/integrations`,
  };
}

export const AGENT_CARD_CORS_HEADERS = {
  "Content-Type": "application/json",
  "Cache-Control": "public, max-age=300",
  "Access-Control-Allow-Origin": "*",
} as const;
