import { describe, it, expect } from "bun:test";
import {
  composeStakeholderPack,
  composeAllPacks,
  renderPackMarkdown,
  PACK_AUDIENCES,
  type DecisionBrief,
} from "./stakeholder-pack";

function brief(over: Partial<DecisionBrief> = {}): DecisionBrief {
  return {
    title: "Move checkout to a single page",
    rationale: "Two-step checkout leaked 18% of carts at the address step.",
    status: "approved",
    actor: null,
    humanDecided: true,
    occurredAt: "2026-06-01T00:00:00Z",
    sourceLabel: "Q2 conversion mission",
    evidenceCount: 3,
    outcome: "standing",
    verdict: "validated",
    metricLabel: "conversion",
    metricValue: "+12%",
    ...over,
  };
}

describe("composeStakeholderPack — audience framing", () => {
  it("exec leads with the decision then standing, why, confidence", () => {
    const p = composeStakeholderPack(brief(), "exec");
    expect(p.audience).toBe("exec");
    expect(p.sections[0].heading).toBe("The decision");
    expect(p.sections.map((s) => s.heading)).toContain("Why it matters");
    expect(p.sections.map((s) => s.heading)).toContain("How confident we are");
  });

  it("eng leads with what changed + rationale/constraints + provenance + status", () => {
    const p = composeStakeholderPack(brief(), "eng");
    expect(p.sections[0].heading).toBe("What changed");
    expect(p.sections.map((s) => s.heading)).toContain("Rationale and constraints");
    expect(p.sections.find((s) => s.heading === "Status")?.body).toContain("approved");
  });

  it("board leads with the strategic framing + governance + standing", () => {
    const p = composeStakeholderPack(brief(), "board");
    expect(p.sections[0].heading).toBe("Strategic decision");
    expect(p.sections.map((s) => s.heading)).toContain("Evidence and governance");
  });

  it("the same facts appear, only the lead/emphasis differs across audiences", () => {
    const all = composeAllPacks(brief());
    for (const a of PACK_AUDIENCES) {
      const joined = all[a].sections.map((s) => s.body).join(" ");
      expect(joined).toContain("18% of carts"); // rationale present for all
    }
    // distinct lead sections
    expect(all.exec.sections[0].heading).not.toBe(all.eng.sections[0].heading);
    expect(all.eng.sections[0].heading).not.toBe(all.board.sections[0].heading);
  });
});

describe("composeStakeholderPack — honest degradation", () => {
  it("states missing rationale plainly rather than inventing one", () => {
    const p = composeStakeholderPack(brief({ rationale: null }), "exec");
    expect(p.sections.find((s) => s.heading === "Why it matters")?.body).toContain(
      "No rationale was recorded",
    );
  });

  it("surfaces superseded standing and a missed outcome honestly", () => {
    const p = composeStakeholderPack(brief({ outcome: "superseded", verdict: "missed" }), "board");
    const standing = p.sections.find((s) => s.heading === "Standing and outcome")?.body ?? "";
    expect(standing).toContain("revised by a later call");
    expect(standing).toContain("it missed");
  });

  it("frames an agent-proposed, no-evidence call without claiming human review", () => {
    const p = composeStakeholderPack(
      brief({
        humanDecided: false,
        actor: "scout",
        evidenceCount: 0,
        sourceLabel: null,
        verdict: null,
      }),
      "exec",
    );
    const conf = p.sections.find((s) => s.heading === "How confident we are")?.body ?? "";
    expect(conf).toContain("Proposed by the scout agent");
    expect(conf).not.toContain("linked piece");
  });

  it("omits the outcome line when no verdict was recorded", () => {
    const p = composeStakeholderPack(brief({ verdict: null }), "exec");
    const where = p.sections.find((s) => s.heading === "Where it stands")?.body ?? "";
    expect(where).not.toContain("Recorded outcome");
  });
});

describe("renderPackMarkdown — artifact", () => {
  it("renders headings + bodies + footer with the as-of stamp", () => {
    const md = renderPackMarkdown(composeStakeholderPack(brief(), "exec"), { asOf: "2026-06-24" });
    expect(md).toContain("# Executive brief: Move checkout to a single page");
    expect(md).toContain("As of 2026-06-24");
    expect(md).toContain("## Why it matters");
    expect(md).toContain("Generated by Cadence");
  });

  it("has no em/en dashes or AI-cliché fingerprints", () => {
    const md = renderPackMarkdown(composeStakeholderPack(brief(), "board"));
    expect(md.includes("—")).toBe(false);
    expect(md.includes("–")).toBe(false);
    expect(md.toLowerCase()).not.toContain("delve");
  });
});
