import { describe, it, expect } from "bun:test";
import { toSlackMrkdwn, isSlackDigestDue } from "./slack-digest.server";

describe("toSlackMrkdwn (JNY-05)", () => {
  it("converts a heading line to a bold line (Slack has no heading syntax)", () => {
    expect(toSlackMrkdwn("# Decision brief")).toBe("*Decision brief*");
    expect(toSlackMrkdwn("## Rationale")).toBe("*Rationale*");
  });

  it("converts markdown's double-asterisk bold to Slack's single-asterisk bold", () => {
    expect(toSlackMrkdwn("This is **important** news")).toBe("This is *important* news");
  });

  it("leaves underscore italics untouched (Slack already uses this syntax)", () => {
    expect(toSlackMrkdwn("_As of 2026-07-03_")).toBe("_As of 2026-07-03_");
  });

  it("neutralizes a literal @channel/@here/@everyone mass-ping directive", () => {
    expect(toSlackMrkdwn("Ship it <!channel> today")).toBe("Ship it &lt;!channel&gt; today");
    expect(toSlackMrkdwn("<!here> heads up")).toBe("&lt;!here&gt; heads up");
  });

  it("neutralizes a literal user-mention directive", () => {
    expect(toSlackMrkdwn("cc <@U0123ABC>")).toBe("cc &lt;@U0123ABC&gt;");
  });

  it("neutralizes a spoofed-link directive (rendered plain, not as a clickable link)", () => {
    const attack = "See <https://evil.example|the doc>";
    const out = toSlackMrkdwn(attack);
    expect(out).toBe("See &lt;https://evil.example|the doc&gt;");
    expect(out).not.toContain("<https://evil.example");
  });

  it("escapes a bare ampersand so Slack doesn't misparse a partial entity", () => {
    expect(toSlackMrkdwn("Growth & Retention")).toBe("Growth &amp; Retention");
  });

  it("handles a full renderPackMarkdown-shaped document", () => {
    const markdown = [
      "# Ship the new pricing page",
      "As of 2026-07-03",
      "",
      "## Rationale",
      "Converts **significantly** better in tests",
      "",
      "_Generated by Supaprod_",
    ].join("\n");
    const out = toSlackMrkdwn(markdown);
    expect(out).toContain("*Ship the new pricing page*");
    expect(out).toContain("*Rationale*");
    expect(out).toContain("Converts *significantly* better in tests");
    expect(out).toContain("_Generated by Supaprod_");
    expect(out).not.toContain("##");
    expect(out).not.toContain("**");
  });
});

describe("isSlackDigestDue (JNY-05)", () => {
  const now = Date.parse("2026-07-03T12:00:00.000Z");

  it("is due when there is no prior post stamp", () => {
    expect(isSlackDigestDue(undefined, now)).toBe(true);
    expect(isSlackDigestDue(null, now)).toBe(true);
  });

  it("is due when the stamp is malformed (fails safe toward posting, not silence)", () => {
    expect(isSlackDigestDue("not-a-date", now)).toBe(true);
    expect(isSlackDigestDue(42, now)).toBe(true);
  });

  it("is NOT due when the last post was less than ~20h ago", () => {
    const recent = new Date(now - 5 * 60 * 60 * 1000).toISOString();
    expect(isSlackDigestDue(recent, now)).toBe(false);
  });

  it("is due when the last post was 20h or more ago", () => {
    const old = new Date(now - 21 * 60 * 60 * 1000).toISOString();
    expect(isSlackDigestDue(old, now)).toBe(true);
  });
});
