import { describe, it, expect } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { debtIn, REPO_ROOT, RETIRED_MARKERS } from "./meridian-ratchet-scan";

/**
 * THE TOP OF SRC, AND THE HALF OF THE HOLE THAT NEEDED NO RULING.
 *
 * ── THE HOLE, AND IT IS NOW CLOSED ON BOTH SIDES ────────────────────────
 * `meridian-ratchet-scan.ts` used to set `SCAN_ROOTS = ["src/components",
 * "src/routes"]` and nothing else, so every file sitting DIRECTLY in `src/` was
 * invisible to it. That is AGENTS.md §9's `src/styles.css`-versus-`src/styles/`
 * trap one level up: two directories are named and the files beside them are not.
 * `src/router.tsx` was carrying four retired `--text-*` uses when this was found,
 * and it is not a marginal file -- it owns `RouteError`, the route-level error
 * fallback that mounts on the public parchment routes as well as the dark app. So
 * the one surface a person reads BECAUSE something already broke was painting
 * from a retired layer, and the ratchet reported a clean tree throughout.
 *
 * **UPDATED 2026-08-21. THE RATCHET NOW SCANS THIS TOO, so the paragraph that
 * used to sit here calling the hole open is no longer true.** `SCAN_SCOPES`
 * carries `src/*` as a shallow scope, `src/server.ts` is recorded in the baseline
 * at its 8 literals, and `src/router.tsx` records zero, because a colour inside
 * `var(--mrd-*, <fallback>)` is no longer counted as raw colour.
 *
 * WHY IT TOOK TWO PASSES, KEPT BECAUSE IT IS THE USEFUL PART. Widening the roots
 * was built first and `design:ratchet` REFUSED to write the baseline, since
 * bringing files into scope is indistinguishable from adding debt to a script
 * whose one job is to refuse the second. The refusal was correct and the widening
 * was reverted rather than forced. What shipped in the meantime was this guard,
 * enforcing only the rule with no precondition:
 *
 *   A RETIRED MARKER means "this file speaks a language the product retired".
 *   That is wrong in every file, always, with no precondition.
 *
 *   A RAW COLOUR means "this hardcodes a colour where a token belongs", and that
 *   rule PRESUMES A REACHABLE TOKEN LAYER. `router.tsx` mounts before the token
 *   layers load, and `server.ts`'s `renderBrandedErrorPage()` is the catastrophic
 *   500 fallback, a standalone HTML document whose comment states the app
 *   stylesheet may be unreachable.
 *
 * The ruling settled both halves without lowering either rule: `router.tsx` reads
 * its Meridian tokens FIRST and degrades to a literal, which is the arrangement
 * the rule wants rather than the one it forbids, so it counts zero; `server.ts`
 * has no `var()` at all, so its 8 are recorded where a reader can audit them, and
 * from now on a NEW literal in either file fails the build.
 *
 * ── SO WHY IS THIS FILE STILL HERE ──────────────────────────────────────
 * Because the two guards fail in different ways and the difference is not
 * cosmetic. The ratchet is a RATCHET: a retired marker at the top of `src` fails
 * it only if the count goes UP, and `server.ts` is now permitted 8 raw colours
 * forever. This guard is a BAN, on retired vocabulary only, with no baseline and
 * nothing to permit -- there is no number here that anybody can grow into. It
 * also fails with the offending path in one line rather than a JSON diff, and it
 * pins the file list as non-empty, so the top of `src` cannot go quiet by having
 * a scope silently renamed out from under it.
 *
 * It overlaps the ratchet on every marker it counts, and that overlap is the
 * cheap half of it. **Whether the overlap is worth a second file is the founder's
 * call, not this file's.**
 *
 * IT READS THE RATCHET'S OWN LEXER RATHER THAN A SECOND COPY. `debtIn` strips
 * comments the same way, counts the same markers, and gains any marker added
 * later for free. A private regex here would be the two-lists-drifting defect
 * this repo has already paid for in `settings-sections.ts`.
 */

/** Files sitting DIRECTLY in `src`, never recursing: the ones no root covers. */
function topLevelFiles(): string[] {
  const dir = join(REPO_ROOT, "src");
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) continue;
    if (!/\.(tsx|ts)$/.test(entry)) continue;
    // Generated, and regenerated by a command rather than edited. AGENTS.md §3
    // forbids hand-editing it, so failing a build on its contents would demand
    // an edit the rules refuse. The scanner exempts it by name for the same
    // reason (`GENERATED_FILES`); this reads the directory itself rather than
    // asking the scanner, so that emptying a scope cannot make this guard go
    // quiet -- the same argument as the marker-list pin below.
    if (entry === "routeTree.gen.ts") continue;
    // Tests are exempt in the ratchet for a stated reason: a guard's whole job
    // can be to assert a legacy literal is still present. Same exemption here.
    if (/\.test\.(ts|tsx)$/.test(entry)) continue;
    out.push(full);
  }
  return out;
}

describe("no file at the top of src speaks a retired design system", () => {
  const files = topLevelFiles();

  it("finds the files at all, so this cannot pass by scanning nothing", () => {
    // A guard whose input is empty is decoration, and this one reads a directory
    // listing, which is exactly the kind of input that can silently become
    // empty. `router.tsx` is named because it is the file the hole was found in.
    expect(files.length).toBeGreaterThanOrEqual(3);
    expect(files.some((f) => f.endsWith("router.tsx"))).toBe(true);
  });

  it("carries no retired marker", () => {
    const offences: string[] = [];
    for (const file of files) {
      const debt = debtIn(readFileSync(file, "utf8"));
      for (const [id, count] of Object.entries(debt)) {
        // `raw-colour` is the rule with a precondition, and it is the RATCHET's
        // to enforce now that `src/*` is a scanned scope: `server.ts` is recorded
        // at 8 and may not grow. Skipped here because this guard is a flat ban
        // with no baseline, and a flat ban is the wrong shape for a rule whose
        // answer depends on whether a token layer is reachable.
        if (id === "raw-colour") continue;
        offences.push(`${file.slice(REPO_ROOT.length + 1)} carries ${count}x ${id}`);
      }
    }
    // Sorted so a failure reads the same way twice and a diff is legible.
    expect(offences.sort()).toEqual([]);
  });

  it("is reading the ratchet's real marker list, not a private copy", () => {
    // If `RETIRED_MARKERS` were ever emptied or renamed, the assertion above
    // would pass by finding nothing. Pinning two of the markers by id means the
    // guard fails loudly instead of going quiet.
    const ids = RETIRED_MARKERS.map((m) => m.id);
    expect(ids).toContain("--text-");
    expect(ids).toContain("--sp-");
    expect(ids.length).toBeGreaterThan(8);
  });
});
