import { describe, it, expect } from "bun:test";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { debtIn, REPO_ROOT, RETIRED_MARKERS } from "./meridian-ratchet-scan";

/**
 * THE RATCHET CANNOT SEE THE TOP OF THE TREE IT GUARDS, AND THIS IS THE HALF OF
 * THAT HOLE THAT NEEDS NO RULING.
 *
 * THE HOLE. `meridian-ratchet-scan.ts` sets `SCAN_ROOTS = ["src/components",
 * "src/routes"]`, so every file sitting DIRECTLY in `src/` is invisible to it.
 * That is AGENTS.md §9's `src/styles.css`-versus-`src/styles/` trap one level up:
 * two directories are named and the files beside them are not. `src/router.tsx`
 * was carrying three retired `--text-*` uses when this was found, and it is not a
 * marginal file -- it owns `RouteError`, the route-level error fallback that
 * mounts on the public parchment routes as well as the dark app. So the one
 * surface a person reads BECAUSE something already broke was painting from a
 * retired layer, and the ratchet reported a clean tree throughout.
 *
 * WHY THIS IS A SEPARATE GUARD RATHER THAN A WIDER `SCAN_ROOTS`. Widening the
 * roots was built, proven to work, and then REFUSED by `design:ratchet`, which
 * would not write a baseline that raises permitted debt:
 *
 *   src/router.tsx  raw-colour: 0 -> 4
 *   src/server.ts   raw-colour: 0 -> 14
 *
 * The refusal is correct and the widening was reverted rather than forced,
 * because a guard that can be talked past is not a guard. But it conflates two
 * rules that are not equally applicable here:
 *
 *   A RETIRED MARKER means "this file speaks a language the product retired".
 *   That is wrong in every file, always, with no precondition.
 *
 *   A RAW COLOUR means "this hardcodes a colour where a token belongs". That
 *   rule has a PRECONDITION -- a reachable token layer -- and these two files
 *   provably do not meet it, each saying so in its own comment. `router.tsx`
 *   mounts before the token layers load, and `server.ts`'s
 *   `renderBrandedErrorPage()` is the catastrophic 500 fallback, a standalone
 *   HTML document whose comment states the app stylesheet may be unreachable.
 *   Its literals were re-resolved to Meridian's own values on 2026-08-21 and it
 *   still needs literals, because there is nothing there to read a token from.
 *
 * So this guard enforces the rule that applies unconditionally and stays silent
 * on the one that does not. **Whether the ratchet itself should widen, and how it
 * should treat a colour inside `var(--mrd-*, <fallback>)`, is still an open
 * question for the founder.** This closes the vocabulary half of it today
 * without pre-empting that decision or touching the baseline.
 *
 * IT READS THE RATCHET'S OWN LEXER RATHER THAN A SECOND COPY. `debtIn` strips
 * comments the same way, counts the same markers, and gains any marker added
 * later for free. A private regex here would be the two-lists-drifting defect
 * this repo has already paid for in `settings-sections.ts`.
 */

/** Files sitting DIRECTLY in `src`, never recursing: the ones no root covers. */
function topLevelFiles(): string[] {
  const dir = join(REPO_ROOT, "src");
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) continue;
    if (!/\.(tsx|ts)$/.test(entry)) continue;
    // Generated, and regenerated by a command rather than edited. AGENTS.md §3
    // forbids hand-editing it, so failing a build on its contents would demand
    // an edit the rules refuse.
    if (entry === "routeTree.gen.ts") continue;
    // Tests are exempt in the ratchet for a stated reason: a guard's whole job
    // can be to assert a legacy literal is still present. Same exemption here.
    if (/\.test\.(ts|tsx)$/.test(entry)) continue;
    out.push(full);
  }
  return out;
}

describe("no file at the top of src speaks a retired design system", () => {
  const files = topLevelFiles();

  it("finds the files at all, so this cannot pass by scanning nothing", () => {
    // A guard whose input is empty is decoration, and this one reads a directory
    // listing, which is exactly the kind of input that can silently become
    // empty. `router.tsx` is named because it is the file the hole was found in.
    expect(files.length).toBeGreaterThanOrEqual(3);
    expect(files.some((f) => f.endsWith("router.tsx"))).toBe(true);
  });

  it("carries no retired marker", () => {
    const offences: string[] = [];
    for (const file of files) {
      const debt = debtIn(readFileSync(file, "utf8"));
      for (const [id, count] of Object.entries(debt)) {
        // `raw-colour` is the one rule with a precondition these files do not
        // meet. See the header: it is deliberately not enforced here, and that
        // is not the same as it being acceptable.
        if (id === "raw-colour") continue;
        offences.push(`${file.slice(REPO_ROOT.length + 1)} carries ${count}x ${id}`);
      }
    }
    // Sorted so a failure reads the same way twice and a diff is legible.
    expect(offences.sort()).toEqual([]);
  });

  it("is reading the ratchet's real marker list, not a private copy", () => {
    // If `RETIRED_MARKERS` were ever emptied or renamed, the assertion above
    // would pass by finding nothing. Pinning two of the markers by id means the
    // guard fails loudly instead of going quiet.
    const ids = RETIRED_MARKERS.map((m) => m.id);
    expect(ids).toContain("--text-");
    expect(ids).toContain("--sp-");
    expect(ids.length).toBeGreaterThan(8);
  });
});
