/*
 * REGENERATE src/components/meridian/brand-glyphs.gen.ts FROM PUBLISHED BRAND ART.
 *
 *   bun run scripts/fetch-brand-glyphs.ts
 *
 * ── WHY THIS IS A SCRIPT AND NOT A HAND-MAINTAINED FILE ─────────────────
 * Because the alternative was measured and it failed twice on 2026-08-23.
 * Linear's mark was three straight strokes somebody drew freehand, and every
 * other "official" mark was a single monochrome silhouette lifted from
 * simple-icons, so Slack, a four-colour logo, shipped as one flat shape.
 *
 * Path data cannot be reviewed by eye. Nobody reads 2,000 characters of bezier
 * and notices it is the wrong company. So it is fetched from the publisher and
 * converted mechanically, and the output is generated rather than edited. The
 * founder's instruction was "do not invent that, use the original thing", and a
 * script is the only version of that promise anyone can check.
 *
 * ── SOURCES ─────────────────────────────────────────────────────────────
 * gilbarbara/logos first: it publishes true multi-path multi-fill brand SVGs,
 * which is the whole point. simple-icons second, for marks it does not carry;
 * those are monochrome by design, which is correct for brands whose mark IS
 * monochrome and wrong for anything else, so nothing colourful falls back to it.
 */

const GILBARBARA = "https://cdn.jsdelivr.net/gh/gilbarbara/logos@main/logos";
const SIMPLE = "https://unpkg.com/simple-icons@latest/icons";

/** provider id in `source-marks.tsx` -> the file that publishes its mark. */
const SOURCES: Record<string, string> = {
  slack: `${GILBARBARA}/slack-icon.svg`,
  linear: `${GILBARBARA}/linear-icon.svg`,
  notion: `${GILBARBARA}/notion-icon.svg`,
  figma: `${GILBARBARA}/figma.svg`,
  jira: `${GILBARBARA}/jira.svg`,
  github: `${GILBARBARA}/github-icon.svg`,
  intercom: `${GILBARBARA}/intercom-icon.svg`,
  zendesk: `${GILBARBARA}/zendesk-icon.svg`,
  /*
   * SIMPLE-ICONS FOR THESE TWO, DELIBERATELY, AND IT IS THE ONE PLACE MONOCHROME
   * IS THE RIGHT ANSWER. gilbarbara publishes the full LOCKUP for both: HubSpot
   * at 512x149 and Stripe at 512x214, mark plus wordmark. Fitted into a 16px
   * square that wordmark is roughly four pixels tall, which is not a logo, it is
   * a smudge. Founder, looking at it: "you have used text plus mark logo, which
   * is not readable".
   *
   * simple-icons only ever publishes the MARK, never a lockup, which is exactly
   * what a 16px slot needs. They arrive without fill and take the brand's own
   * colour from `--mrd-brand-*` below.
   */
  stripe: `${SIMPLE}/stripe.svg`,
  hubspot: `${SIMPLE}/hubspot.svg`,
  salesforce: `${GILBARBARA}/salesforce.svg`,
  gmail: `${GILBARBARA}/google-gmail.svg`,
  google_calendar: `${GILBARBARA}/google-calendar.svg`,
  microsoft_outlook: `${GILBARBARA}/microsoft-icon.svg`,
  microsoft_mail: `${GILBARBARA}/microsoft-icon.svg`,
  google_docs: `${SIMPLE}/googledocs.svg`,
  google_tasks: `${SIMPLE}/googletasks.svg`,
};

/*
 * Brands whose published mark is black or near-black. They point at
 * `--mrd-brand-*` so the ground decides which of the brand's OWN two published
 * variants shows: the real hex on paper, the light-on-dark asset on the dark
 * canvas. Every one of these companies ships both. Colour is never invented
 * here and never replaced with an interface hue; a monochrome brand simply
 * stays monochrome, which is what it is.
 */
const MONOCHROME_BRANDS = new Set([
  // Single-colour marks that carry their brand hue through the token.
  "hubspot",
  "stripe",
  "github",
  "linear",
  "notion",
  "intercom",
  "zendesk",
  "google_docs",
  "google_tasks",
]);

/** Atlassian's flat blue. Two Jira paths reference gradient `<defs>` that do not
 *  travel with path data; its third path already carries this exact value. */
const JIRA_FLAT = "#2684FF";

type Part = { d: string; fill: string | null };

function polygonToPath(points: string): string | null {
  const nums = points.match(/-?\d*\.?\d+/g);
  if (!nums || nums.length < 4) return null;
  const pairs: string[] = [];
  for (let i = 0; i + 1 < nums.length; i += 2) pairs.push(`${nums[i]},${nums[i + 1]}`);
  return `M${pairs.join(" L")} Z`;
}

function parse(svg: string): { viewBox: string; parts: Part[] } {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1] ?? "0 0 24 24";
  const parts: Part[] = [];
  for (const m of svg.matchAll(/<path\b([^>]*?)\/?>/g)) {
    const d = m[1].match(/\bd="([^"]+)"/)?.[1];
    if (d) parts.push({ d, fill: m[1].match(/\bfill="([^"]+)"/)?.[1] ?? null });
  }
  for (const m of svg.matchAll(/<polygon\b([^>]*?)\/?>/g)) {
    const pts = m[1].match(/\bpoints="([^"]+)"/)?.[1];
    const d = pts ? polygonToPath(pts) : null;
    if (d) parts.push({ d, fill: m[1].match(/\bfill="([^"]+)"/)?.[1] ?? null });
  }
  return { viewBox, parts };
}

const HEADER = `/*
 * OFFICIAL BRAND GEOMETRY AND OFFICIAL BRAND COLOUR.
 *
 * GENERATED by \`bun run scripts/fetch-brand-glyphs.ts\`. Do not hand edit: fix
 * the script or the source list and regenerate. That script's header carries
 * the full argument for why this is generated rather than drawn.
 *
 * In short, two defects the founder found in the rendered product. Linear was
 * three freehand strokes and not Linear's mark at all. And every other mark was
 * a single monochrome silhouette from simple-icons, so Slack, whose logo is four
 * colours, shipped as one flat shape. Gmail is five colours, Google Calendar
 * seven, Figma five, Microsoft four.
 *
 * Marks pointing at \`--mrd-brand-*\` are the brands whose published mark is
 * black or near-black. The token carries the real hex on the light ground and
 * the brand's own light-on-dark asset on the dark one. No mark is given a hue it
 * does not have.
 */

export type BrandGlyph = {
  viewBox: string;
  parts: ReadonlyArray<{ d: string; fill?: string }>;
};

export const BRAND_GLYPHS: Record<string, BrandGlyph> = {
`;

async function main() {
  const ids = Object.keys(SOURCES).sort();
  const blocks: string[] = [];
  for (const id of ids) {
    const res = await fetch(SOURCES[id]);
    if (!res.ok) throw new Error(`${id}: ${SOURCES[id]} answered ${res.status}`);
    const { viewBox, parts: raw } = parse(await res.text());
    if (raw.length === 0)
      throw new Error(`${id}: no drawable shapes found, refusing to emit an empty mark`);

    let parts = raw;
    // Notion publishes a white backing plate under the mark. On any ground but
    // white it is wrong, and the black path IS the mark.
    if (id === "notion") parts = parts.filter((p) => !/^#(fff|ffffff)$/i.test(p.fill ?? ""));
    if (id === "jira")
      parts = parts.map((p) => ({ ...p, fill: p.fill?.startsWith("url(") ? JIRA_FLAT : p.fill }));

    const token = `var(--mrd-brand-${id.replace(/_/g, "-")})`;
    const body = parts
      .map((p) => {
        const d = p.d.replace(/\s+/g, " ").trim().replace(/\\/g, "\\\\").replace(/"/g, '\\"');
        const fill = MONOCHROME_BRANDS.has(id) ? token : (p.fill ?? "currentColor");
        return `    { d: "${d}", fill: "${fill}" },`;
      })
      .join("\n");
    blocks.push(`  ${id}: {\n    viewBox: "${viewBox}",\n    parts: [\n${body}\n    ],\n  },`);
    console.log(`  ${id.padEnd(18)} ${parts.length} part(s)  ${viewBox}`);
  }
  const out = `${HEADER}${blocks.join("\n")}\n};\n`;
  await Bun.write("src/components/meridian/brand-glyphs.gen.ts", out);
  console.log(
    `\nwrote src/components/meridian/brand-glyphs.gen.ts (${out.length} bytes, ${ids.length} brands)`,
  );
}

await main();
