#!/usr/bin/env bash
# lane.sh - cross-worktree ATOMIC claim ledger for the parallel build lanes.
#
# WHY THIS EXISTS
#   A git working tree is a PRIVATE view: a claim written into one worktree's
#   feature-dashboard.md is invisible to the sibling worktrees until it is
#   committed, pushed, AND the sibling pulls. That gap is a race window where
#   two lanes pick the SAME item. This ledger removes the race by living OUTSIDE
#   every worktree (a fixed shared path) and using an ATOMIC primitive every
#   lane can see instantly.
#
#   Atomicity: POSIX `mkdir` either creates the dir or fails - never half-does
#   it - so `mkdir claims/<ID>` is a race-free mutex. If two lanes claim the
#   same ID at the same instant, exactly one mkdir wins; the loser gets EEXIST
#   and picks another item. No daemon, no database, no lock library.
#
#   Beyond the per-item mutex, each claim also RESERVES the file globs it will
#   touch. Before a claim is granted, its globs are checked against every other
#   active claim; an overlap is rejected. That generalises the old static
#   file-disjoint lane model to dynamic, roam-the-whole-dashboard picking: two
#   lanes can never hold overlapping files even when they pull different items.
#
# LEDGER LOCATION  ${CADENCE_LEDGER:-$HOME/.cadence-parallel}
#   claims/<ID>/meta   one dir per claimed item; `meta` is key=value lines.
#   LANES.md           human-readable registry (regenerated by `list`).
#
# SUBCOMMANDS
#   lane.sh init
#   lane.sh claim <ID> <lane> "glob1,glob2,..." ["note"]   # exit 0 won, 1 held, 3 file-conflict
#   lane.sh pin   <ID> <lane> "glob1,glob2,..." ["note"]   # like claim but reap-proof (area reservation)
#   lane.sh release <ID>
#   lane.sh heartbeat <ID>                                  # keep a long build's claim fresh
#   lane.sh list                                            # all active claims
#   lane.sh board                                           # per-lane view: Lane 0..4 -> current item
#   lane.sh mine <lane>                                     # this lane's active claims
#   lane.sh held <ID>                                       # print holder line if claimed, else nothing
#   lane.sh reap [ttl_hours]                                # auto-release UNPINNED claims older than ttl (default 6h)
#
# EXIT CODES (claim):  0 = claimed, 1 = already held by someone, 3 = file-glob conflict
set -uo pipefail

LEDGER="${CADENCE_LEDGER:-$HOME/.cadence-parallel}"
CLAIMS="$LEDGER/claims"

# DONE registry: the ledger remembers recently-COMPLETED items (not just active claims),
# so `claim` REFUSES an item another lane already finished - the mechanical fix so two
# sessions never re-pick the same done work. `lane.sh done <ID>` records a completion;
# `reap` prunes old markers (by then the ✅ is in the register, caught by `git pull`).
DONE="$LEDGER/done"
# Flip the status field (column 3) of the matching register row to NEW_STATUS, then
# IMMEDIATELY commit + push that change to origin/main so the founder's view of the
# dashboard is always live, regardless of which lane branch the agent is on.
# Uses a temporary git worktree on origin/main so there is never a conflict with
# the lane branch's unrelated code changes.
_flip_dashboard_row() {
  local id="$1" new_status="$2" commit_msg="${3:-}"
  local reg; reg="$(_register_path)"
  local root; root="$(_repo_root)"
  [ -f "$reg" ] || return 0
  local row_awk='
    /^\| [0-9]+ \|/{
      v=$4; gsub(/^[ \t]+|[ \t]+$/,"",v);
      if (v==want) { $3=ns }
    }
    { print }
  '

  # 1) Update the file in the current worktree too (so the lane branch's own
  #    local state matches immediately, e.g. if this call's push below fails
  #    and a human inspects the working copy). This copy is NEVER what gets
  #    pushed (see step 2) — it can be stale relative to origin/main between
  #    fetches, and blindly shipping a stale copy is exactly the bug fixed
  #    below.
  local tmp; tmp="${reg}.lane_tmp.$$"
  awk -F'|' -v OFS='|' -v want="$id" -v ns=" $new_status " "$row_awk" \
    "$reg" > "$tmp" && mv "$tmp" "$reg" || rm -f "$tmp"

  # 2) PUSH the dashboard change to origin/main in a temp worktree so the founder's
  #    view is updated immediately — not deferred to the lane branch's next merge.
  #    This is the permanent fix for "main dashboard stays stale while lanes build."
  #
  #    BUG HISTORY (2026-07-02, founder-reported: claims silently never showed up
  #    on the dashboard, across every lane, repeatedly): the `git commit` call
  #    below placed `-q` AFTER the `-- "$rel_reg"` pathspec separator, so git
  #    parsed `-q` as a literal filename ("pathspec '-q' did not match any
  #    file(s)") and the commit failed on EVERY SINGLE claim. The `2>/dev/null`
  #    on that line, plus this function's old unconditional `return 0`, hid the
  #    failure completely — callers always saw "PUSHED TO MAIN" whether or not
  #    anything actually landed. Fixed: `-q` moved before `--`, both push
  #    attempts are now checked, and the function returns non-zero (so the
  #    caller's existing WARN fallback actually fires) when the push did not
  #    land. Also dropped the `-q` on `worktree remove` (unsupported by this
  #    git version — "unknown switch `q'" — which broke cleanup and could
  #    orphan worktree registrations over many claims).
  #
  #    SECOND BUG (found immediately after fixing the first, by actually
  #    exercising the push for the first time ever): this step used to `cp
  #    "$reg"` — the LOCAL working-copy file from step 1 — into the temp
  #    worktree and commit THAT. If the caller's local file was behind
  #    origin/main (any other lane pushed a row change since this lane's last
  #    fetch — routine in a multi-lane setup), that stale snapshot overwrote
  #    every row the other lane had just landed, a silent lost-update race.
  #    It clobbered a real completed row within minutes of first being
  #    exercised. Fixed: the awk row-edit now runs directly against the temp
  #    worktree's copy (checked out fresh off origin/main), so this call only
  #    ever touches its own row and can never regress anyone else's.
  local pushed=1
  if [ -n "$commit_msg" ] && git -C "$root" rev-parse --git-dir >/dev/null 2>&1; then
    git -C "$root" fetch -q origin main 2>/dev/null || true
    local tmp_wt; tmp_wt=$(mktemp -d 2>/dev/null) || return 1
    local rel_reg; rel_reg="${reg#$root/}"
    # Add worktree on main (detached), edit ITS OWN fresh copy, commit, push, clean up
    if git -C "$root" worktree add --detach "$tmp_wt" origin/main -q 2>/dev/null; then
      local wtmp; wtmp="$tmp_wt/$rel_reg.wt_tmp.$$"
      if [ -f "$tmp_wt/$rel_reg" ] && \
        awk -F'|' -v OFS='|' -v want="$id" -v ns=" $new_status " "$row_awk" \
          "$tmp_wt/$rel_reg" > "$wtmp"; then
        mv "$wtmp" "$tmp_wt/$rel_reg"
      else
        rm -f "$wtmp"
      fi
      git -C "$tmp_wt" add "$rel_reg" 2>/dev/null
      if git -C "$tmp_wt" -c user.name="lane.sh" -c user.email="lane@cadence.local" \
        commit --no-verify -q -m "$commit_msg" -- "$rel_reg" 2>/dev/null; then
        # Push; retry once on failure after a fresh fetch + re-apply the row edit
        # (a rebase would replay the commit's OLD snapshot verbatim, reintroducing
        # the exact lost-update race this function exists to prevent).
        if git -C "$tmp_wt" push origin HEAD:refs/heads/main -q 2>/dev/null; then
          pushed=0
        else
          git -C "$tmp_wt" reset -q --hard origin/main 2>/dev/null
          git -C "$tmp_wt" fetch -q origin main 2>/dev/null || true
          git -C "$tmp_wt" reset -q --hard origin/main 2>/dev/null
          if [ -f "$tmp_wt/$rel_reg" ] && \
            awk -F'|' -v OFS='|' -v want="$id" -v ns=" $new_status " "$row_awk" \
              "$tmp_wt/$rel_reg" > "$wtmp"; then
            mv "$wtmp" "$tmp_wt/$rel_reg"
            git -C "$tmp_wt" add "$rel_reg" 2>/dev/null
            if git -C "$tmp_wt" -c user.name="lane.sh" -c user.email="lane@cadence.local" \
              commit --no-verify -q -m "$commit_msg" -- "$rel_reg" 2>/dev/null && \
              git -C "$tmp_wt" push origin HEAD:refs/heads/main -q 2>/dev/null; then
              pushed=0
            fi
          else
            rm -f "$wtmp"
          fi
        fi
      fi
      git -C "$root" worktree remove --force "$tmp_wt" 2>/dev/null || rm -rf "$tmp_wt"
    else
      rm -rf "$tmp_wt"
    fi
  fi
  return "$pushed"
}
_sync_board() { :; }   # retired 2026-06-21 as a SEPARATE board file; dashboard writes now go through _flip_dashboard_row above

_now() { date +%s; }
_die() { echo "lane.sh: $*" >&2; exit 2; }

_ensure() { mkdir -p "$CLAIMS" 2>/dev/null || true; }

# Map a logical claim id to a filesystem-safe, SINGLE-segment dir name. The mkdir
# mutex (and every claimed-check) needs ONE path segment, but register-row ids can
# contain '/' (e.g. "M1 / LRN-01", "LCH-01 / L1"). A raw '/' splits the path into
# nested segments whose parent does not exist, so `mkdir "$CLAIMS/$id"` fails ->
# the code misreads EEXIST-vs-ENOENT as "HELD" and the item is unclaimable FOREVER
# (it also never matches the `[ -d "$CLAIMS/$id" ]` claimed-check, so `next` keeps
# offering it). Replacing ONLY '/' keeps every id that already worked (spaces,
# parens, dots are valid single-segment chars) byte-identical, so this is a pure
# unblock of slash-ids with zero impact on prior/active claims. The LOGICAL id is
# still stored verbatim in meta's id= field, so display and dedup are unaffected.
_cdir() { printf '%s' "${1//\//_}"; }

# meta is simple key=value lines so it parses with no jq dependency.
_meta_get() { # <claimdir> <key>
  local f="$1/meta" k="$2"
  [ -f "$f" ] || return 1
  sed -n "s/^$k=//p" "$f" | head -1
}

# Reduce a glob to its literal directory/prefix (everything before the first
# wildcard), trailing slash stripped. `src/lib/incidents*.ts` -> `src/lib/incidents`
_glob_prefix() {
  local g="$1"
  g="${g%%\**}"   # cut at first *
  g="${g%%\?*}"   # cut at first ?
  g="${g%/}"
  printf '%s' "$g"
}

# 0 (true) if globs A and B can touch the same path. Conservative: a bare
# wildcard (empty prefix) overlaps everything.
_globs_overlap() { # <csvA> <csvB>
  local a b pa pb
  IFS=',' read -ra _A <<< "$1"
  IFS=',' read -ra _B <<< "$2"
  for a in "${_A[@]}"; do
    a="${a# }"; a="${a% }"; [ -z "$a" ] && continue
    pa="$(_glob_prefix "$a")"
    for b in "${_B[@]}"; do
      b="${b# }"; b="${b% }"; [ -z "$b" ] && continue
      pb="$(_glob_prefix "$b")"
      if [ -z "$pa" ] || [ -z "$pb" ]; then return 0; fi   # bare * -> overlaps all
      case "$pa" in "$pb"*) return 0;; esac
      case "$pb" in "$pa"*) return 0;; esac
    done
  done
  return 1
}

# Path to the feature-dashboard register (the single ranked source of truth).
_register_path() {
  printf '%s' "$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." 2>/dev/null && pwd)/docs/planning/feature-dashboard.md"
}

# 0 (true) if <id> is an EXACT register-row id (the 3rd `|`-field of a `| N | status | id |`
# row). Used to warn against private sub-ids that bypass the register-item mutex (the cause
# of repeated cross-session duplication: a sub-id claim leaves the whole register item still
# showing as eligible in `lane.sh next`, so a second lane picks it).
_is_register_id() {
  local id="$1" reg; reg="$(_register_path)"
  [ -f "$reg" ] || return 1
  awk -F'|' -v want="$id" '
    /^\| [0-9]+ \|/{ v=$4; gsub(/^[ \t]+|[ \t]+$/,"",v); if (v==want){found=1; exit} }
    END{ exit(found?0:1) }
  ' "$reg"
}

# Repo root for the worktree this script lives in.
_repo_root() { cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." 2>/dev/null && pwd; }

# Read the FRESHEST register. The collision bug (two lanes on one item) is a STALE-READ
# race: `next` picks from THIS worktree's local dashboard, but a sibling lane may have
# ALREADY flipped that row to `🔨 In Dev` + pushed to origin/main; until this worktree
# pulls, its local copy still shows the row eligible, so both lanes target it. Fixing the
# read at the source: fetch origin (fast, refs-only) and read `origin/main`'s dashboard, so
# `next`/`claim` see what every other lane has already committed. Falls back to the local
# file when offline / not a git repo / `LANE_NO_FETCH=1` (tests). This is what makes
# "pick only items no other session is handling" true even before this lane rebases.
_fresh_register() {
  local root; root="$(_repo_root)"
  if [ "${LANE_NO_FETCH:-}" != "1" ] && git -C "$root" rev-parse --git-dir >/dev/null 2>&1; then
    git -C "$root" fetch -q origin main 2>/dev/null || true
    git -C "$root" show origin/main:docs/planning/feature-dashboard.md 2>/dev/null && return 0
  fi
  cat "$root/docs/planning/feature-dashboard.md" 2>/dev/null
}

# Print the lane number currently holding <id> as `🔨 In Dev (laneN, ...)` in the FRESH
# register, or nothing. Used by `claim` as a SECOND, independent lock (besides the ledger
# mutex): a row another lane has flipped In-Dev on origin must never be claimed here, even
# if that lane's ledger claim was reaped or the timing lagged.
_indev_lane_of() {
  local id="$1"
  _fresh_register | awk -F'|' -v want="$id" '
    /^\| [0-9]+ \|/{
      v=$4; gsub(/^[ \t]+|[ \t]+$/,"",v);
      if (v==want) {
        s=$3; gsub(/^[ \t]+|[ \t]+$/,"",s);
        if (s ~ /^🔨/ && s ~ /In Dev \(/) {
          t=s; sub(/.*In Dev \(/,"",t); sub(/[,)].*/,"",t);
          gsub(/^[ \t]+|[ \t]+$/,"",t); print t;
        }
        exit
      }
    }'
}

cmd_init() { _ensure; echo "ledger ready at $LEDGER"; }

cmd_claim() {
  local id="${1:-}" lane="${2:-}" globs="${3:-}" note="${4:-}"
  [ -n "$id" ] && [ -n "$lane" ] || _die "usage: claim <ID> <lane> \"globs\" [note]"
  _ensure
  local cdir; cdir="$(_cdir "$id")"
  local dir="$CLAIMS/$cdir"

  # 0) already COMPLETED by another lane? refuse - do NOT redo finished work.
  if [ -e "$DONE/$cdir" ]; then
    echo "DONE $id (already completed: $(cat "$DONE/$cdir" 2>/dev/null)); pick another item"
    return 4
  fi

  # 1) atomic per-item mutex
  if ! mkdir "$dir" 2>/dev/null; then
    local h; h="$(_meta_get "$dir" lane 2>/dev/null || echo '?')"
    echo "HELD $id by lane $h (since $(_meta_get "$dir" started 2>/dev/null))"
    return 1
  fi

  # 1.5) dashboard In-Dev cross-check (SECOND, independent lock). The ledger mutex above only
  #      sees ACTIVE ledger claims; a sibling lane may have flipped this row `🔨 In Dev` on
  #      origin/main without a live ledger claim (timing lag, or a reaped claim). Refuse if so,
  #      so two lanes never work the same item even across the ledger/dashboard gap. (Pins and
  #      same-lane re-claims are exempt: a pin is a deliberate area reservation; a lane re-claiming
  #      its own in-dev row is the umbrella-continue case.)
  if [ "${PINNED:-false}" != "true" ]; then
    local indev; indev="$(_indev_lane_of "$id" 2>/dev/null || true)"
    if [ -n "$indev" ] && [ "$indev" != "$lane" ] && [ "$indev" != "lane $lane" ] && [ "$indev" != "lane${lane}" ]; then
      rmdir "$dir" 2>/dev/null || rm -rf "$dir"   # back out my just-won mutex
      echo "IN-DEV $id is 🔨 In Dev by lane $indev on origin/main; pick another item"
      return 1
    fi
  fi

  # 2) file-glob reservation: reject if my globs overlap ANOTHER LANE's active claim.
  #    A lane never conflicts with its own claims/reservations (one lane = one
  #    worker, building one item at a time; its area-reservation must not block
  #    its own per-item claim). So overlap is only checked across DIFFERENT lanes.
  if [ -n "$globs" ]; then
    local other og ol oid
    for other in "$CLAIMS"/*/; do
      [ -d "$other" ] || continue
      [ "$other" = "$dir/" ] && continue
      ol="$(_meta_get "${other%/}" lane 2>/dev/null || echo '?')"
      [ "$ol" = "$lane" ] && continue                 # same lane -> never a conflict
      og="$(_meta_get "${other%/}" globs 2>/dev/null || true)"
      [ -n "$og" ] || continue
      if _globs_overlap "$globs" "$og"; then
        oid="$(basename "${other%/}")"
        rmdir "$dir" 2>/dev/null || rm -rf "$dir"     # back out my just-won mutex
        echo "CONFLICT $id globs overlap lane $ol's claim $oid ($og)"
        return 3
      fi
    done
  fi

  # 3) record meta
  local ts; ts="$(_now)"
  {
    echo "id=$id"
    echo "lane=$lane"
    echo "globs=$globs"
    echo "note=$note"
    echo "pinned=${PINNED:-false}"
    echo "pid=$$"
    echo "host=$(hostname 2>/dev/null || echo unknown)"
    echo "started=$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null)"
    echo "epoch=$ts"
    echo "beat=$ts"
  } > "$dir/meta"
  if [ "${PINNED:-false}" = "true" ]; then
    echo "PINNED $id by lane $lane"
  else
    echo "CLAIMED $id by lane $lane"
    # Immediately flip the dashboard row to 🔨 In Dev AND push to origin/main so the
    # founder's view is live without any manual agent step.
    local indev_label; indev_label="🔨 In Dev (lane${lane}, $(date '+%Y-%m-%d'))"
    local claim_msg; claim_msg="chore(lane${lane}): claim $id — 🔨 In Dev"
    if _flip_dashboard_row "$id" "$indev_label" "$claim_msg"; then
      echo "DASHBOARD UPDATED + PUSHED TO MAIN: row '$id' → $indev_label"
    else
      echo "WARN: could not auto-flip dashboard row for '$id' — update feature-dashboard.md manually" >&2
    fi
  fi
  # Anti-duplication guard: a private sub-id (e.g. claiming "DBR-EDGE-CONF" instead of the
  # register row "DBR (H1)") leaves the whole item still eligible in every other lane's
  # `lane.sh next`, so a second lane re-picks it and wastes effort. Claim the REGISTER id.
  if [ "${PINNED:-false}" != "true" ] && ! _is_register_id "$id"; then
    echo "WARN: '$id' is not a feature-dashboard register-row id." >&2
    echo "      If this is sub-work of a tracked item, claim that item's REGISTER id instead" >&2
    echo "      (so every other lane's \`lane.sh next\` excludes the whole item and never" >&2
    echo "      duplicates it). Only claim a non-register id for genuinely new / meta work." >&2
  fi
  _sync_board
  return 0
}

cmd_pin() { PINNED=true cmd_claim "$@"; }

cmd_release() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: release <ID>"
  local dir="$CLAIMS/$(_cdir "$id")"
  if [ -d "$dir" ]; then rm -rf "$dir"; echo "RELEASED $id"; else echo "not held: $id"; fi
}

# `done <ID>`: mark an item fully COMPLETED (✅). Frees the active claim AND records a DONE
# marker so no other lane re-picks it. Call this only on a true ✅ completion; a ◐ partial
# uses `release` instead (it stays re-pickable so a later lane can continue the remainder).
cmd_done() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: done <ID>"
  _ensure; mkdir -p "$DONE"
  local cdir; cdir="$(_cdir "$id")"
  rm -rf "${CLAIMS:?}/$cdir" 2>/dev/null || true
  echo "$(date '+%Y-%m-%d %H:%M:%S' 2>/dev/null) lane=${2:-?}" > "$DONE/$cdir"
  echo "DONE-RECORDED $id (claim freed; future claims refused)"
  # Flip the dashboard status row to ✅ AND push to origin/main immediately.
  # Agents should still update the row detail cell and re-run dashboard-tally.sh
  # to refresh the % numbers, then commit+push THOSE prose changes too.
  local done_msg; done_msg="done(lane${2:-?}): $id ✅ complete"
  if _flip_dashboard_row "$id" "✅" "$done_msg"; then
    echo "DASHBOARD UPDATED + PUSHED TO MAIN: row '$id' → ✅"
    echo ">>> NEXT: update the row detail cell + re-run 'bash scripts/dashboard-tally.sh' + commit + push <<<"
  else
    echo "WARN: could not auto-flip dashboard row for '$id' to ✅ — update manually" >&2
  fi
}

# `next [count]`: DETERMINISTICALLY print the next eligible item IDs (lowest Rank first) -
# this is "what to build next" with ZERO judgment. Eligible = register status ⬜ or ◐
# (a ◐ is partial = it HAS remaining work, so it is ALWAYS continue-able, never "skip as
# done") AND priority is an autonomous tier (Tier 1 or Tier 3; Tier 2 design + Tier 4 polish
# are founder-prompted) AND not currently claimed AND not in the DONE registry. The lane runs
# `for id in $(lane.sh next); do lane.sh claim "$id" <lane> "<globs>" && build && break; done`.
# Empty output (exit 2) = the board is GENUINELY dry; anything else means build it, never long-poll.
cmd_next() {
  local count="${1:-500}" rank id n=0   # effectively the full eligible list (claim down it until one wins)
  _ensure
  # Read FRESH (origin/main) eligibility, not this worktree's possibly-stale local copy, so a
  # row a sibling lane already flipped `🔨 In Dev` + pushed is excluded here too (it is no
  # longer ⬜/◐). This is the source-level fix for the stale-read collision.
  while IFS=$'\t' read -r rank id; do
    local cdir; cdir="$(_cdir "$id")"
    [ -d "$CLAIMS/$cdir" ] && continue      # already claimed by a lane (ledger mutex)
    [ -e "$DONE/$cdir" ] && continue        # already completed (no re-pick)
    echo "$id"
    n=$((n + 1)); [ "$n" -ge "$count" ] && break
  done < <(_fresh_register | awk -F'|' '
    /^\| [0-9]+ \|/{
      r=$2; s=$3; id=$4; pr=$8;
      gsub(/^[ \t]+|[ \t]+$/,"",r); gsub(/^[ \t]+|[ \t]+$/,"",s); gsub(/^[ \t]+|[ \t]+$/,"",id); gsub(/^[ \t]+|[ \t]+$/,"",pr);
      if ((s=="\342\254\234" || s=="\342\227\220") && (pr=="Tier 1" || pr=="Tier 3")) printf "%d\t%s\n", r, id;
    }' | sort -n)
  if [ "$n" = 0 ]; then echo "BOARD DRY: no eligible Tier-1/Tier-3 ⬜/◐ item unclaimed + not done" >&2; return 2; fi
  return 0
}

cmd_heartbeat() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: heartbeat <ID>"
  local f="$CLAIMS/$(_cdir "$id")/meta"
  [ -f "$f" ] || { echo "not held: $id"; return 1; }
  local ts; ts="$(_now)"
  if grep -q '^beat=' "$f"; then
    sed -i.bak "s/^beat=.*/beat=$ts/" "$f" && rm -f "$f.bak"
  else
    echo "beat=$ts" >> "$f"
  fi
  echo "beat $id"
}

cmd_held() {
  local id="${1:-}"; [ -n "$id" ] || _die "usage: held <ID>"
  local dir="$CLAIMS/$(_cdir "$id")"
  [ -d "$dir" ] || return 0
  echo "$id lane=$(_meta_get "$dir" lane) globs=$(_meta_get "$dir" globs) since=$(_meta_get "$dir" started)"
}

_print_claims() { # <lane-filter-or-empty>
  local filter="${1:-}" dir id lane globs started beat now age any=0
  now="$(_now)"
  for dir in "$CLAIMS"/*/; do
    [ -d "$dir" ] || continue
    id="$(_meta_get "${dir%/}" id 2>/dev/null)"; [ -n "$id" ] || id="$(basename "${dir%/}")"
    lane="$(_meta_get "${dir%/}" lane)"
    [ -n "$filter" ] && [ "$lane" != "$filter" ] && continue
    globs="$(_meta_get "${dir%/}" globs)"
    started="$(_meta_get "${dir%/}" started)"
    beat="$(_meta_get "${dir%/}" beat)"; [ -n "$beat" ] || beat="$(_meta_get "${dir%/}" epoch)"
    age="?"; [ -n "$beat" ] && age="$(( (now - beat) / 60 ))m"
    local pin=""; [ "$(_meta_get "${dir%/}" pinned)" = "true" ] && pin=" [pinned]"
    printf '  %-22s lane=%-3s age=%-6s globs=%s%s\n' "$id" "${lane:-?}" "$age" "${globs:-<none>}" "$pin"
    any=1
  done
  if [ "$any" = 0 ]; then echo "  (no active claims)"; fi
  return 0
}

cmd_board() { # per-lane "who is building what right now"
  _ensure
  echo "Parallel build board (live @ $LEDGER):"
  local n dir item lane pinned found now beat age
  now="$(_now)"
  for n in 0 1 2 3 4; do
    found=""
    for dir in "$CLAIMS"/*/; do
      [ -d "$dir" ] || continue
      [ "$(_meta_get "${dir%/}" lane)" = "$n" ] || continue
      [ "$(_meta_get "${dir%/}" pinned)" = "true" ] && continue   # area reservations are not a "task"
      beat="$(_meta_get "${dir%/}" beat)"; [ -n "$beat" ] || beat="$(_meta_get "${dir%/}" epoch)"
      age=""; [ -n "$beat" ] && age=" ($(( (now - beat)/60 ))m)"
      local bid; bid="$(_meta_get "${dir%/}" id 2>/dev/null)"; [ -n "$bid" ] || bid="$(basename "${dir%/}")"
      found="$found ${bid}${age}"
    done
    printf '  Lane %s: %s\n' "$n" "${found:-(idle / no active claim)}"
  done
  local anyres=0
  for dir in "$CLAIMS"/*/; do
    [ -d "$dir" ] || continue
    [ "$(_meta_get "${dir%/}" pinned)" = "true" ] || continue
    [ "$anyres" = 0 ] && { echo "  --- standing reservations (safety, not a lane task) ---"; anyres=1; }
    printf '  [reserved] %-12s lane=%s\n' "$(basename "${dir%/}")" "$(_meta_get "${dir%/}" lane)"
  done
  return 0
}

cmd_list() { echo "Active claims @ $LEDGER:"; _ensure; _print_claims ""; }
cmd_mine() { local lane="${1:-}"; [ -n "$lane" ] || _die "usage: mine <lane>"; echo "Lane $lane claims:"; _ensure; _print_claims "$lane"; }

cmd_reap() {
  local ttl_h="${1:-6}" ttl_s dir beat now id
  ttl_s=$(( ttl_h * 3600 )); now="$(_now)"; _ensure
  for dir in "$CLAIMS"/*/; do
    [ -d "$dir" ] || continue
    id="$(_meta_get "${dir%/}" id 2>/dev/null)"; [ -n "$id" ] || id="$(basename "${dir%/}")"
    [ "$(_meta_get "${dir%/}" pinned)" = "true" ] && continue   # reservations never expire
    beat="$(_meta_get "${dir%/}" beat)"; [ -n "$beat" ] || beat="$(_meta_get "${dir%/}" epoch)"
    [ -n "$beat" ] || continue
    if [ "$(( now - beat ))" -gt "$ttl_s" ]; then
      rm -rf "$dir"; echo "REAPED $id (stale > ${ttl_h}h)"
    fi
  done
  # prune DONE markers older than 48h (by then the ✅ is in the register, caught by git pull)
  if [ -d "$DONE" ]; then
    find "$DONE" -type f -mmin +2880 -delete 2>/dev/null || true
  fi
}

sub="${1:-}"; shift || true
case "$sub" in
  init)      cmd_init "$@" ;;
  claim)     cmd_claim "$@" ;;
  pin)       cmd_pin "$@" ;;
  release)   cmd_release "$@" ;;
  done)      cmd_done "$@" ;;
  next)      cmd_next "$@" ;;
  heartbeat) cmd_heartbeat "$@" ;;
  list)      cmd_list "$@" ;;
  board)     cmd_board "$@" ;;
  mine)      cmd_mine "$@" ;;
  held)      cmd_held "$@" ;;
  reap)      cmd_reap "$@" ;;
  ""|-h|--help|help)
    sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//' ;;
  *) _die "unknown subcommand: $sub (try: init|claim|release|heartbeat|list|mine|held|reap)" ;;
esac
