/**
 * WHAT MERIDIAN ACTUALLY EXPORTS, which is not what `ls meridian/` shows.
 *
 * Written 2026-08-23 after TWO rulings in one evening turned on the same hole.
 * `surface-parts.tsx` alone exports `Region`, `Pre`, `Action`, `Approve` and more,
 * so the directory listing shows no `Block.tsx` and no `Pre.tsx`, and a careful
 * reader concludes those components do not exist:
 *
 *   - REQ-L0-005 asked MAIN LANE to BUILD `Block` and `Pre` equivalents. Both
 *     already existed, in `surface-parts.tsx`, and `Pre` had been written
 *     specifically to replace the retired `.sp-pre`.
 *   - RL0-004 ruled that Meridian had no touch-target rule, from grepping
 *     `min-height` in `meridian.css`. The rule is a Tailwind utility inside
 *     `CONTROL_SHAPE` in a `.tsx` file. Same error, made by the reviewer.
 *
 * WHY THIS IS A GENERATED LIST AND NOT AN `index.ts` BARREL. A barrel is the
 * obvious fix and it would break the adoption metric. `scripts/meridian-adoption.ts`
 * counts a component as adopted by matching the import SOURCE:
 *
 *     from "@/components/meridian/<Component>"
 *
 * An import routed through a barrel does not match that, so every component
 * imported the new way would silently report as UNADOPTED, and the number that
 * tells us whether Meridian is actually being used would decay as adoption rose.
 * A lookup problem is not worth blinding a metric for. Deep imports stay.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DIR = join(import.meta.dir, "..", "src/components/meridian");
const OUT = join(DIR, "COMPONENTS.md");

const rows: { name: string; file: string; kind: string }[] = [];
for (const file of readdirSync(DIR).filter((f) => /\.tsx?$/.test(f))) {
  const src = readFileSync(join(DIR, file), "utf8");
  for (const m of src.matchAll(/^export (function|const|type|interface) ([A-Za-z0-9_]+)/gm)) {
    rows.push({ name: m[2], file, kind: m[1] });
  }
}
rows.sort((a, b) => a.name.localeCompare(b.name));

/* Components first: a lane hunting "does Meridian have X" wants the renderable
   thing, not a prop type that happens to sort next to it. */
const isComponent = (r: (typeof rows)[number]) =>
  r.kind === "function" && /^[A-Z]/.test(r.name);
const comps = rows.filter(isComponent);
const rest = rows.filter((r) => !isComponent(r));

const line = (r: (typeof rows)[number]) => `| \`${r.name}\` | \`${r.file}\` | ${r.kind} |`;

writeFileSync(
  OUT,
  `# What Meridian exports

<!-- GENERATED by scripts/meridian-exports.ts. Do not hand-edit; run \`bun run meridian:exports\`. -->

**\`ls\` this directory and you will not find \`Block.tsx\` or \`Pre.tsx\`, and you will
conclude those components do not exist. They do.** \`surface-parts.tsx\` alone carries
${rows.filter((r) => r.file === "surface-parts.tsx").length} exports. Search this table before
filing a \`meridian-gap\` request.

There is deliberately **no \`index.ts\` barrel** -- it would break the adoption metric,
which matches on the deep import path. Import from the file named here.

## Components (${comps.length})

| Export | File | |
| --- | --- | --- |
${comps.map(line).join("\n")}

## Types, constants and helpers (${rest.length})

| Export | File | Kind |
| --- | --- | --- |
${rest.map(line).join("\n")}
`,
);
console.log(`meridian: ${comps.length} components, ${rest.length} other exports -> ${OUT}`);
