/**
 * Re-freeze the Meridian ratchet baseline. `bun run design:ratchet`
 *
 * RUN THIS TO RECORD DEBT YOU HAVE REMOVED, never to silence a failure. The
 * ratchet failing on a NEW file or a GROWN count is the guard doing its job;
 * widening the baseline to make that pass is the one move that breaks it, and
 * it breaks it permanently and silently.
 *
 * The script prints what it is about to do and refuses to raise any count, so
 * the wrong use is not merely discouraged, it is unavailable.
 */

import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { join } from "node:path";

import {
  REPO_ROOT,
  scan,
  totalDebt,
  type DebtLedger,
} from "../src/__tests__/meridian-ratchet-scan";

const BASELINE_PATH = join(REPO_ROOT, "src/__tests__/meridian-ratchet.baseline.json");

const previous: DebtLedger = existsSync(BASELINE_PATH)
  ? (JSON.parse(readFileSync(BASELINE_PATH, "utf8")).files as DebtLedger)
  : {};
const current = scan();

const first = Object.keys(previous).length === 0;
const grew: string[] = [];
const shrank: string[] = [];
const newlyMeasured: string[] = [];

/*
 * WIDENING THE GUARD IS NOT RAISING THE DEBT, and telling the two apart is the
 * whole subtlety of this script.
 *
 * When a marker is ADDED to the scanner -- as `import:shell/primitives` was on
 * 2026-08-15, after the first version was found to report a file as clean while
 * it composed entirely from retired components -- every file's count for that
 * marker goes from an implicit zero to its real value. That looks identical to
 * debt being added, and the refusal below would block it forever, which would
 * mean THE GUARD COULD NEVER BE MADE HONEST once shipped.
 *
 * So a marker the baseline has never recorded ANYWHERE is treated as newly
 * measured rather than newly incurred. It was always there; nothing was
 * counting it. A marker the baseline already knows about may still only go
 * down, which is the rule that does the work.
 */
const knownMarkers = new Set(Object.values(previous).flatMap((f) => Object.keys(f)));

for (const file of new Set([...Object.keys(previous), ...Object.keys(current)])) {
  const markers = new Set([
    ...Object.keys(previous[file] ?? {}),
    ...Object.keys(current[file] ?? {}),
  ]);
  for (const m of markers) {
    const was = previous[file]?.[m] ?? 0;
    const now = current[file]?.[m] ?? 0;
    if (now > was) {
      if (!first && !knownMarkers.has(m)) newlyMeasured.push(`  ${file}  ${m}: ${now}`);
      else grew.push(`  ${file}  ${m}: ${was} -> ${now}`);
    }
    if (now < was) shrank.push(`  ${file}  ${m}: ${was} -> ${now}`);
  }
}

if (newlyMeasured.length > 0) {
  console.log(
    [
      "",
      `A NEW MARKER IS BEING MEASURED FOR THE FIRST TIME (${newlyMeasured.length} entries).`,
      "This RAISES the recorded total without any debt having been added: the",
      "scanner simply started counting something that was always there. The",
      "baseline is being made more honest, not more permissive.",
      "",
      ...newlyMeasured.slice(0, 8),
      newlyMeasured.length > 8 ? `  ... and ${newlyMeasured.length - 8} more` : "",
      "",
    ]
      .filter(Boolean)
      .join("\n"),
  );
}

if (!first && grew.length > 0) {
  console.error(
    [
      "",
      "REFUSING TO WRITE. This would RAISE the permitted debt:",
      "",
      ...grew,
      "",
      "The baseline only ever moves down. If a file genuinely needs more",
      "retired vocabulary, the honest answer is almost always that Meridian is",
      "missing something -- build it there instead. See",
      "docs/design/DESIGN-SYSTEM.md.",
      "",
    ].join("\n"),
  );
  process.exit(1);
}

writeFileSync(
  BASELINE_PATH,
  `${JSON.stringify(
    {
      _comment: [
        "THE MERIDIAN RATCHET BASELINE. Generated by `bun run design:ratchet`.",
        "This is the retired-design-system debt each file is permitted to carry.",
        "It only ever moves DOWN. A file absent from this list must be clean.",
        "Do not hand-edit; do not regenerate to silence a failure.",
      ],
      totalOccurrences: totalDebt(current),
      fileCount: Object.keys(current).length,
      files: Object.fromEntries(Object.entries(current).sort(([a], [b]) => a.localeCompare(b))),
    },
    null,
    2,
  )}\n`,
);

console.log(
  [
    "",
    first ? "Meridian ratchet baseline created." : "Meridian ratchet baseline re-frozen.",
    `  files carrying debt : ${Object.keys(current).length}`,
    `  total occurrences   : ${totalDebt(current)}`,
    shrank.length > 0 ? `  reclaimed this pass : ${shrank.length} counts` : "",
    "",
    ...shrank.slice(0, 20),
    shrank.length > 20 ? `  ... and ${shrank.length - 20} more` : "",
    "",
  ]
    .filter(Boolean)
    .join("\n"),
);
