/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SubprocessorsRouteImport } from './routes/subprocessors'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as DSlugRouteImport } from './routes/d.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTrustLedgerRouteImport } from './routes/_authenticated.trust-ledger'
import { Route as AuthenticatedTracesRouteImport } from './routes/_authenticated.traces'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated.today'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedSyncRouteImport } from './routes/_authenticated.sync'
import { Route as AuthenticatedSwarmRouteImport } from './routes/_authenticated.swarm'
import { Route as AuthenticatedStakeholderRouteImport } from './routes/_authenticated.stakeholder'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated.roadmap'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated.prompts'
import { Route as AuthenticatedProductRouteImport } from './routes/_authenticated.product'
import { Route as AuthenticatedPrdsRouteImport } from './routes/_authenticated.prds'
import { Route as AuthenticatedOutcomeRouteImport } from './routes/_authenticated.outcome'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated.opportunities'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedObserveRouteImport } from './routes/_authenticated.observe'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated.memory'
import { Route as AuthenticatedMeetingsRouteImport } from './routes/_authenticated.meetings'
import { Route as AuthenticatedLearnRouteImport } from './routes/_authenticated.learn'
import { Route as AuthenticatedKnowledgeRouteImport } from './routes/_authenticated.knowledge'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated.integrations'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedImpactRouteImport } from './routes/_authenticated.impact'
import { Route as AuthenticatedGuardrailsRouteImport } from './routes/_authenticated.guardrails'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated.governance'
import { Route as AuthenticatedGovernRouteImport } from './routes/_authenticated.govern'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated.fleet'
import { Route as AuthenticatedEvalsRouteImport } from './routes/_authenticated.evals'
import { Route as AuthenticatedEvalHealthRouteImport } from './routes/_authenticated.eval-health'
import { Route as AuthenticatedDriftRouteImport } from './routes/_authenticated.drift'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated.docs'
import { Route as AuthenticatedDiscoveryRouteImport } from './routes/_authenticated.discovery'
import { Route as AuthenticatedDelegateRouteImport } from './routes/_authenticated.delegate'
import { Route as AuthenticatedCockpitRouteImport } from './routes/_authenticated.cockpit'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated.chat'
import { Route as AuthenticatedChangelogRouteImport } from './routes/_authenticated.changelog'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedBudgetsRouteImport } from './routes/_authenticated.budgets'
import { Route as AuthenticatedBriefingRouteImport } from './routes/_authenticated.briefing'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated.agents'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated.studio.index'
import { Route as AuthenticatedPrdsIndexRouteImport } from './routes/_authenticated.prds.index'
import { Route as AuthenticatedMissionsIndexRouteImport } from './routes/_authenticated.missions.index'
import { Route as AuthenticatedBuildIndexRouteImport } from './routes/_authenticated.build.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiPublicIngestSignalsRouteImport } from './routes/api/public/ingest-signals'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedTracesTraceIdRouteImport } from './routes/_authenticated.traces.$traceId'
import { Route as AuthenticatedStudioMissionIdRouteImport } from './routes/_authenticated.studio.$missionId'
import { Route as AuthenticatedPrdsIdRouteImport } from './routes/_authenticated.prds.$id'
import { Route as AuthenticatedMissionsMissionIdRouteImport } from './routes/_authenticated.missions.$missionId'
import { Route as AuthenticatedMeetingsIdRouteImport } from './routes/_authenticated.meetings.$id'
import { Route as AuthenticatedBuildMissionIdRouteImport } from './routes/_authenticated.build.$missionId'
import { Route as AuthenticatedAdminWorkspacesRouteImport } from './routes/_authenticated.admin.workspaces'
import { Route as AuthenticatedAdminPricingRouteImport } from './routes/_authenticated.admin.pricing'
import { Route as AuthenticatedAdminPlatformRouteImport } from './routes/_authenticated.admin.platform'
import { Route as AuthenticatedAdminPeopleRouteImport } from './routes/_authenticated.admin.people'
import { Route as AuthenticatedAdminObservabilityRouteImport } from './routes/_authenticated.admin.observability'
import { Route as AuthenticatedAdminAiCostsRouteImport } from './routes/_authenticated.admin.ai-costs'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksTriggerTickRouteImport } from './routes/api/public/hooks/trigger-tick'
import { Route as ApiPublicHooksStewardTickRouteImport } from './routes/api/public/hooks/steward-tick'
import { Route as ApiPublicHooksSenseTickRouteImport } from './routes/api/public/hooks/sense-tick'
import { Route as ApiPublicHooksScoutTickRouteImport } from './routes/api/public/hooks/scout-tick'
import { Route as ApiPublicHooksRetentionTickRouteImport } from './routes/api/public/hooks/retention-tick'
import { Route as ApiPublicHooksResumeRunsRouteImport } from './routes/api/public/hooks/resume-runs'
import { Route as ApiPublicHooksResearcherTickRouteImport } from './routes/api/public/hooks/researcher-tick'
import { Route as ApiPublicHooksOutcomeTickRouteImport } from './routes/api/public/hooks/outcome-tick'
import { Route as ApiPublicHooksMemoryTickRouteImport } from './routes/api/public/hooks/memory-tick'
import { Route as ApiPublicHooksIndexerTickRouteImport } from './routes/api/public/hooks/indexer-tick'
import { Route as ApiPublicHooksEventReactorTickRouteImport } from './routes/api/public/hooks/event-reactor-tick'
import { Route as ApiPublicHooksEvalTickRouteImport } from './routes/api/public/hooks/eval-tick'
import { Route as ApiPublicHooksEvalSuiteTickRouteImport } from './routes/api/public/hooks/eval-suite-tick'
import { Route as ApiPublicHooksDriftTickRouteImport } from './routes/api/public/hooks/drift-tick'
import { Route as ApiPublicHooksDeriveTickRouteImport } from './routes/api/public/hooks/derive-tick'
import { Route as ApiPublicHooksDelegatePollTickRouteImport } from './routes/api/public/hooks/delegate-poll-tick'
import { Route as ApiPublicHooksCreditTickRouteImport } from './routes/api/public/hooks/credit-tick'
import { Route as ApiPublicHooksClusterTickRouteImport } from './routes/api/public/hooks/cluster-tick'
import { Route as ApiPublicHooksApprovalsTickRouteImport } from './routes/api/public/hooks/approvals-tick'
import { Route as ApiPublicHooksAgentTickRouteImport } from './routes/api/public/hooks/agent-tick'
import { Route as ApiPublicHooksAdminExpiryTickRouteImport } from './routes/api/public/hooks/admin-expiry-tick'
import { Route as ApiPublicA2aTasksRouteImport } from './routes/api/public/a2a.tasks'
import { Route as ApiPublicConnectGithubCallbackRouteImport } from './routes/api/public/connect/github/callback'
import { Route as ApiPublicA2aMessageStreamRouteImport } from './routes/api/public/a2a.message.stream'
import { Route as ApiPublicA2aMessageSendRouteImport } from './routes/api/public/a2a.message.send'
import { Route as ApiPublicA2aAgentsCadenceCardRouteImport } from './routes/api/public/a2a.agents.cadence.card'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SubprocessorsRoute = SubprocessorsRouteImport.update({
  id: '/subprocessors',
  path: '/subprocessors',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrustLedgerRoute =
  AuthenticatedTrustLedgerRouteImport.update({
    id: '/trust-ledger',
    path: '/trust-ledger',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTracesRoute = AuthenticatedTracesRouteImport.update({
  id: '/traces',
  path: '/traces',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyncRoute = AuthenticatedSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSwarmRoute = AuthenticatedSwarmRouteImport.update({
  id: '/swarm',
  path: '/swarm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStakeholderRoute =
  AuthenticatedStakeholderRouteImport.update({
    id: '/stakeholder',
    path: '/stakeholder',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductRoute = AuthenticatedProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrdsRoute = AuthenticatedPrdsRouteImport.update({
  id: '/prds',
  path: '/prds',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutcomeRoute = AuthenticatedOutcomeRouteImport.update({
  id: '/outcome',
  path: '/outcome',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedObserveRoute = AuthenticatedObserveRouteImport.update({
  id: '/observe',
  path: '/observe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingsRoute = AuthenticatedMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnRoute = AuthenticatedLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeRoute = AuthenticatedKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImpactRoute = AuthenticatedImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuardrailsRoute = AuthenticatedGuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGovernRoute = AuthenticatedGovernRouteImport.update({
  id: '/govern',
  path: '/govern',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEvalsRoute = AuthenticatedEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEvalHealthRoute = AuthenticatedEvalHealthRouteImport.update({
  id: '/eval-health',
  path: '/eval-health',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriftRoute = AuthenticatedDriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoveryRoute = AuthenticatedDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDelegateRoute = AuthenticatedDelegateRouteImport.update({
  id: '/delegate',
  path: '/delegate',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCockpitRoute = AuthenticatedCockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangelogRoute = AuthenticatedChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBudgetsRoute = AuthenticatedBudgetsRouteImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBriefingRoute = AuthenticatedBriefingRouteImport.update({
  id: '/briefing',
  path: '/briefing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPrdsIndexRoute = AuthenticatedPrdsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPrdsRoute,
} as any)
const AuthenticatedMissionsIndexRoute =
  AuthenticatedMissionsIndexRouteImport.update({
    id: '/missions/',
    path: '/missions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBuildIndexRoute = AuthenticatedBuildIndexRouteImport.update({
  id: '/build/',
  path: '/build/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestSignalsRoute = ApiPublicIngestSignalsRouteImport.update({
  id: '/api/public/ingest-signals',
  path: '/api/public/ingest-signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTracesTraceIdRoute =
  AuthenticatedTracesTraceIdRouteImport.update({
    id: '/$traceId',
    path: '/$traceId',
    getParentRoute: () => AuthenticatedTracesRoute,
  } as any)
const AuthenticatedStudioMissionIdRoute =
  AuthenticatedStudioMissionIdRouteImport.update({
    id: '/studio/$missionId',
    path: '/studio/$missionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPrdsIdRoute = AuthenticatedPrdsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedPrdsRoute,
} as any)
const AuthenticatedMissionsMissionIdRoute =
  AuthenticatedMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeetingsIdRoute = AuthenticatedMeetingsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedMeetingsRoute,
} as any)
const AuthenticatedBuildMissionIdRoute =
  AuthenticatedBuildMissionIdRouteImport.update({
    id: '/build/$missionId',
    path: '/build/$missionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminWorkspacesRoute =
  AuthenticatedAdminWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPricingRoute =
  AuthenticatedAdminPricingRouteImport.update({
    id: '/pricing',
    path: '/pricing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatformRoute =
  AuthenticatedAdminPlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPeopleRoute =
  AuthenticatedAdminPeopleRouteImport.update({
    id: '/people',
    path: '/people',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminObservabilityRoute =
  AuthenticatedAdminObservabilityRouteImport.update({
    id: '/observability',
    path: '/observability',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiCostsRoute =
  AuthenticatedAdminAiCostsRouteImport.update({
    id: '/ai-costs',
    path: '/ai-costs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksTriggerTickRoute =
  ApiPublicHooksTriggerTickRouteImport.update({
    id: '/api/public/hooks/trigger-tick',
    path: '/api/public/hooks/trigger-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStewardTickRoute =
  ApiPublicHooksStewardTickRouteImport.update({
    id: '/api/public/hooks/steward-tick',
    path: '/api/public/hooks/steward-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSenseTickRoute = ApiPublicHooksSenseTickRouteImport.update({
  id: '/api/public/hooks/sense-tick',
  path: '/api/public/hooks/sense-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksScoutTickRoute = ApiPublicHooksScoutTickRouteImport.update({
  id: '/api/public/hooks/scout-tick',
  path: '/api/public/hooks/scout-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRetentionTickRoute =
  ApiPublicHooksRetentionTickRouteImport.update({
    id: '/api/public/hooks/retention-tick',
    path: '/api/public/hooks/retention-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResumeRunsRoute =
  ApiPublicHooksResumeRunsRouteImport.update({
    id: '/api/public/hooks/resume-runs',
    path: '/api/public/hooks/resume-runs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResearcherTickRoute =
  ApiPublicHooksResearcherTickRouteImport.update({
    id: '/api/public/hooks/researcher-tick',
    path: '/api/public/hooks/researcher-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOutcomeTickRoute =
  ApiPublicHooksOutcomeTickRouteImport.update({
    id: '/api/public/hooks/outcome-tick',
    path: '/api/public/hooks/outcome-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMemoryTickRoute =
  ApiPublicHooksMemoryTickRouteImport.update({
    id: '/api/public/hooks/memory-tick',
    path: '/api/public/hooks/memory-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIndexerTickRoute =
  ApiPublicHooksIndexerTickRouteImport.update({
    id: '/api/public/hooks/indexer-tick',
    path: '/api/public/hooks/indexer-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEventReactorTickRoute =
  ApiPublicHooksEventReactorTickRouteImport.update({
    id: '/api/public/hooks/event-reactor-tick',
    path: '/api/public/hooks/event-reactor-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEvalTickRoute = ApiPublicHooksEvalTickRouteImport.update({
  id: '/api/public/hooks/eval-tick',
  path: '/api/public/hooks/eval-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEvalSuiteTickRoute =
  ApiPublicHooksEvalSuiteTickRouteImport.update({
    id: '/api/public/hooks/eval-suite-tick',
    path: '/api/public/hooks/eval-suite-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDriftTickRoute = ApiPublicHooksDriftTickRouteImport.update({
  id: '/api/public/hooks/drift-tick',
  path: '/api/public/hooks/drift-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDeriveTickRoute =
  ApiPublicHooksDeriveTickRouteImport.update({
    id: '/api/public/hooks/derive-tick',
    path: '/api/public/hooks/derive-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDelegatePollTickRoute =
  ApiPublicHooksDelegatePollTickRouteImport.update({
    id: '/api/public/hooks/delegate-poll-tick',
    path: '/api/public/hooks/delegate-poll-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCreditTickRoute =
  ApiPublicHooksCreditTickRouteImport.update({
    id: '/api/public/hooks/credit-tick',
    path: '/api/public/hooks/credit-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksClusterTickRoute =
  ApiPublicHooksClusterTickRouteImport.update({
    id: '/api/public/hooks/cluster-tick',
    path: '/api/public/hooks/cluster-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApprovalsTickRoute =
  ApiPublicHooksApprovalsTickRouteImport.update({
    id: '/api/public/hooks/approvals-tick',
    path: '/api/public/hooks/approvals-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentTickRoute = ApiPublicHooksAgentTickRouteImport.update({
  id: '/api/public/hooks/agent-tick',
  path: '/api/public/hooks/agent-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAdminExpiryTickRoute =
  ApiPublicHooksAdminExpiryTickRouteImport.update({
    id: '/api/public/hooks/admin-expiry-tick',
    path: '/api/public/hooks/admin-expiry-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicA2aTasksRoute = ApiPublicA2aTasksRouteImport.update({
  id: '/api/public/a2a/tasks',
  path: '/api/public/a2a/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConnectGithubCallbackRoute =
  ApiPublicConnectGithubCallbackRouteImport.update({
    id: '/api/public/connect/github/callback',
    path: '/api/public/connect/github/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicA2aMessageStreamRoute =
  ApiPublicA2aMessageStreamRouteImport.update({
    id: '/api/public/a2a/message/stream',
    path: '/api/public/a2a/message/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicA2aMessageSendRoute = ApiPublicA2aMessageSendRouteImport.update({
  id: '/api/public/a2a/message/send',
  path: '/api/public/a2a/message/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicA2aAgentsCadenceCardRoute =
  ApiPublicA2aAgentsCadenceCardRouteImport.update({
    id: '/api/public/a2a/agents/cadence/card',
    path: '/api/public/a2a/agents/cadence/card',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/trust': typeof TrustRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cockpit': typeof AuthenticatedCockpitRoute
  '/delegate': typeof AuthenticatedDelegateRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/drift': typeof AuthenticatedDriftRoute
  '/eval-health': typeof AuthenticatedEvalHealthRoute
  '/evals': typeof AuthenticatedEvalsRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/govern': typeof AuthenticatedGovernRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/guardrails': typeof AuthenticatedGuardrailsRoute
  '/impact': typeof AuthenticatedImpactRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/memory': typeof AuthenticatedMemoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/observe': typeof AuthenticatedObserveRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/outcome': typeof AuthenticatedOutcomeRoute
  '/prds': typeof AuthenticatedPrdsRouteWithChildren
  '/product': typeof AuthenticatedProductRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stakeholder': typeof AuthenticatedStakeholderRoute
  '/swarm': typeof AuthenticatedSwarmRoute
  '/sync': typeof AuthenticatedSyncRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/traces': typeof AuthenticatedTracesRouteWithChildren
  '/trust-ledger': typeof AuthenticatedTrustLedgerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/mcp': typeof ApiMcpRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/d/$slug': typeof DSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/admin/ai-costs': typeof AuthenticatedAdminAiCostsRoute
  '/admin/observability': typeof AuthenticatedAdminObservabilityRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/build/$missionId': typeof AuthenticatedBuildMissionIdRoute
  '/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/prds/$id': typeof AuthenticatedPrdsIdRoute
  '/studio/$missionId': typeof AuthenticatedStudioMissionIdRoute
  '/traces/$traceId': typeof AuthenticatedTracesTraceIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ingest-signals': typeof ApiPublicIngestSignalsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/build/': typeof AuthenticatedBuildIndexRoute
  '/missions/': typeof AuthenticatedMissionsIndexRoute
  '/prds/': typeof AuthenticatedPrdsIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/api/public/a2a/tasks': typeof ApiPublicA2aTasksRoute
  '/api/public/hooks/admin-expiry-tick': typeof ApiPublicHooksAdminExpiryTickRoute
  '/api/public/hooks/agent-tick': typeof ApiPublicHooksAgentTickRoute
  '/api/public/hooks/approvals-tick': typeof ApiPublicHooksApprovalsTickRoute
  '/api/public/hooks/cluster-tick': typeof ApiPublicHooksClusterTickRoute
  '/api/public/hooks/credit-tick': typeof ApiPublicHooksCreditTickRoute
  '/api/public/hooks/delegate-poll-tick': typeof ApiPublicHooksDelegatePollTickRoute
  '/api/public/hooks/derive-tick': typeof ApiPublicHooksDeriveTickRoute
  '/api/public/hooks/drift-tick': typeof ApiPublicHooksDriftTickRoute
  '/api/public/hooks/eval-suite-tick': typeof ApiPublicHooksEvalSuiteTickRoute
  '/api/public/hooks/eval-tick': typeof ApiPublicHooksEvalTickRoute
  '/api/public/hooks/event-reactor-tick': typeof ApiPublicHooksEventReactorTickRoute
  '/api/public/hooks/indexer-tick': typeof ApiPublicHooksIndexerTickRoute
  '/api/public/hooks/memory-tick': typeof ApiPublicHooksMemoryTickRoute
  '/api/public/hooks/outcome-tick': typeof ApiPublicHooksOutcomeTickRoute
  '/api/public/hooks/researcher-tick': typeof ApiPublicHooksResearcherTickRoute
  '/api/public/hooks/resume-runs': typeof ApiPublicHooksResumeRunsRoute
  '/api/public/hooks/retention-tick': typeof ApiPublicHooksRetentionTickRoute
  '/api/public/hooks/scout-tick': typeof ApiPublicHooksScoutTickRoute
  '/api/public/hooks/sense-tick': typeof ApiPublicHooksSenseTickRoute
  '/api/public/hooks/steward-tick': typeof ApiPublicHooksStewardTickRoute
  '/api/public/hooks/trigger-tick': typeof ApiPublicHooksTriggerTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/a2a/message/send': typeof ApiPublicA2aMessageSendRoute
  '/api/public/a2a/message/stream': typeof ApiPublicA2aMessageStreamRoute
  '/api/public/connect/github/callback': typeof ApiPublicConnectGithubCallbackRoute
  '/api/public/a2a/agents/cadence/card': typeof ApiPublicA2aAgentsCadenceCardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/trust': typeof TrustRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/briefing': typeof AuthenticatedBriefingRoute
  '/budgets': typeof AuthenticatedBudgetsRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/changelog': typeof AuthenticatedChangelogRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cockpit': typeof AuthenticatedCockpitRoute
  '/delegate': typeof AuthenticatedDelegateRoute
  '/discovery': typeof AuthenticatedDiscoveryRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/drift': typeof AuthenticatedDriftRoute
  '/eval-health': typeof AuthenticatedEvalHealthRoute
  '/evals': typeof AuthenticatedEvalsRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/govern': typeof AuthenticatedGovernRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/guardrails': typeof AuthenticatedGuardrailsRoute
  '/impact': typeof AuthenticatedImpactRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/knowledge': typeof AuthenticatedKnowledgeRoute
  '/learn': typeof AuthenticatedLearnRoute
  '/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/memory': typeof AuthenticatedMemoryRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/observe': typeof AuthenticatedObserveRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/outcome': typeof AuthenticatedOutcomeRoute
  '/product': typeof AuthenticatedProductRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stakeholder': typeof AuthenticatedStakeholderRoute
  '/swarm': typeof AuthenticatedSwarmRoute
  '/sync': typeof AuthenticatedSyncRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/today': typeof AuthenticatedTodayRoute
  '/traces': typeof AuthenticatedTracesRouteWithChildren
  '/trust-ledger': typeof AuthenticatedTrustLedgerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/mcp': typeof ApiMcpRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/d/$slug': typeof DSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/admin/ai-costs': typeof AuthenticatedAdminAiCostsRoute
  '/admin/observability': typeof AuthenticatedAdminObservabilityRoute
  '/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/build/$missionId': typeof AuthenticatedBuildMissionIdRoute
  '/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/prds/$id': typeof AuthenticatedPrdsIdRoute
  '/studio/$missionId': typeof AuthenticatedStudioMissionIdRoute
  '/traces/$traceId': typeof AuthenticatedTracesTraceIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ingest-signals': typeof ApiPublicIngestSignalsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/build': typeof AuthenticatedBuildIndexRoute
  '/missions': typeof AuthenticatedMissionsIndexRoute
  '/prds': typeof AuthenticatedPrdsIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/api/public/a2a/tasks': typeof ApiPublicA2aTasksRoute
  '/api/public/hooks/admin-expiry-tick': typeof ApiPublicHooksAdminExpiryTickRoute
  '/api/public/hooks/agent-tick': typeof ApiPublicHooksAgentTickRoute
  '/api/public/hooks/approvals-tick': typeof ApiPublicHooksApprovalsTickRoute
  '/api/public/hooks/cluster-tick': typeof ApiPublicHooksClusterTickRoute
  '/api/public/hooks/credit-tick': typeof ApiPublicHooksCreditTickRoute
  '/api/public/hooks/delegate-poll-tick': typeof ApiPublicHooksDelegatePollTickRoute
  '/api/public/hooks/derive-tick': typeof ApiPublicHooksDeriveTickRoute
  '/api/public/hooks/drift-tick': typeof ApiPublicHooksDriftTickRoute
  '/api/public/hooks/eval-suite-tick': typeof ApiPublicHooksEvalSuiteTickRoute
  '/api/public/hooks/eval-tick': typeof ApiPublicHooksEvalTickRoute
  '/api/public/hooks/event-reactor-tick': typeof ApiPublicHooksEventReactorTickRoute
  '/api/public/hooks/indexer-tick': typeof ApiPublicHooksIndexerTickRoute
  '/api/public/hooks/memory-tick': typeof ApiPublicHooksMemoryTickRoute
  '/api/public/hooks/outcome-tick': typeof ApiPublicHooksOutcomeTickRoute
  '/api/public/hooks/researcher-tick': typeof ApiPublicHooksResearcherTickRoute
  '/api/public/hooks/resume-runs': typeof ApiPublicHooksResumeRunsRoute
  '/api/public/hooks/retention-tick': typeof ApiPublicHooksRetentionTickRoute
  '/api/public/hooks/scout-tick': typeof ApiPublicHooksScoutTickRoute
  '/api/public/hooks/sense-tick': typeof ApiPublicHooksSenseTickRoute
  '/api/public/hooks/steward-tick': typeof ApiPublicHooksStewardTickRoute
  '/api/public/hooks/trigger-tick': typeof ApiPublicHooksTriggerTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/a2a/message/send': typeof ApiPublicA2aMessageSendRoute
  '/api/public/a2a/message/stream': typeof ApiPublicA2aMessageStreamRoute
  '/api/public/connect/github/callback': typeof ApiPublicConnectGithubCallbackRoute
  '/api/public/a2a/agents/cadence/card': typeof ApiPublicA2aAgentsCadenceCardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/subprocessors': typeof SubprocessorsRoute
  '/trust': typeof TrustRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/briefing': typeof AuthenticatedBriefingRoute
  '/_authenticated/budgets': typeof AuthenticatedBudgetsRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/changelog': typeof AuthenticatedChangelogRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/cockpit': typeof AuthenticatedCockpitRoute
  '/_authenticated/delegate': typeof AuthenticatedDelegateRoute
  '/_authenticated/discovery': typeof AuthenticatedDiscoveryRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/drift': typeof AuthenticatedDriftRoute
  '/_authenticated/eval-health': typeof AuthenticatedEvalHealthRoute
  '/_authenticated/evals': typeof AuthenticatedEvalsRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/govern': typeof AuthenticatedGovernRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/guardrails': typeof AuthenticatedGuardrailsRoute
  '/_authenticated/impact': typeof AuthenticatedImpactRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/knowledge': typeof AuthenticatedKnowledgeRoute
  '/_authenticated/learn': typeof AuthenticatedLearnRoute
  '/_authenticated/meetings': typeof AuthenticatedMeetingsRouteWithChildren
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/observe': typeof AuthenticatedObserveRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/outcome': typeof AuthenticatedOutcomeRoute
  '/_authenticated/prds': typeof AuthenticatedPrdsRouteWithChildren
  '/_authenticated/product': typeof AuthenticatedProductRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stakeholder': typeof AuthenticatedStakeholderRoute
  '/_authenticated/swarm': typeof AuthenticatedSwarmRoute
  '/_authenticated/sync': typeof AuthenticatedSyncRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/traces': typeof AuthenticatedTracesRouteWithChildren
  '/_authenticated/trust-ledger': typeof AuthenticatedTrustLedgerRoute
  '/api/chat': typeof ApiChatRoute
  '/api/mcp': typeof ApiMcpRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/d/$slug': typeof DSlugRoute
  '/join/$token': typeof JoinTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/t/$slug': typeof TSlugRoute
  '/_authenticated/admin/ai-costs': typeof AuthenticatedAdminAiCostsRoute
  '/_authenticated/admin/observability': typeof AuthenticatedAdminObservabilityRoute
  '/_authenticated/admin/people': typeof AuthenticatedAdminPeopleRoute
  '/_authenticated/admin/platform': typeof AuthenticatedAdminPlatformRoute
  '/_authenticated/admin/pricing': typeof AuthenticatedAdminPricingRoute
  '/_authenticated/admin/workspaces': typeof AuthenticatedAdminWorkspacesRoute
  '/_authenticated/build/$missionId': typeof AuthenticatedBuildMissionIdRoute
  '/_authenticated/meetings/$id': typeof AuthenticatedMeetingsIdRoute
  '/_authenticated/missions/$missionId': typeof AuthenticatedMissionsMissionIdRoute
  '/_authenticated/prds/$id': typeof AuthenticatedPrdsIdRoute
  '/_authenticated/studio/$missionId': typeof AuthenticatedStudioMissionIdRoute
  '/_authenticated/traces/$traceId': typeof AuthenticatedTracesTraceIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ingest-signals': typeof ApiPublicIngestSignalsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/build/': typeof AuthenticatedBuildIndexRoute
  '/_authenticated/missions/': typeof AuthenticatedMissionsIndexRoute
  '/_authenticated/prds/': typeof AuthenticatedPrdsIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/api/public/a2a/tasks': typeof ApiPublicA2aTasksRoute
  '/api/public/hooks/admin-expiry-tick': typeof ApiPublicHooksAdminExpiryTickRoute
  '/api/public/hooks/agent-tick': typeof ApiPublicHooksAgentTickRoute
  '/api/public/hooks/approvals-tick': typeof ApiPublicHooksApprovalsTickRoute
  '/api/public/hooks/cluster-tick': typeof ApiPublicHooksClusterTickRoute
  '/api/public/hooks/credit-tick': typeof ApiPublicHooksCreditTickRoute
  '/api/public/hooks/delegate-poll-tick': typeof ApiPublicHooksDelegatePollTickRoute
  '/api/public/hooks/derive-tick': typeof ApiPublicHooksDeriveTickRoute
  '/api/public/hooks/drift-tick': typeof ApiPublicHooksDriftTickRoute
  '/api/public/hooks/eval-suite-tick': typeof ApiPublicHooksEvalSuiteTickRoute
  '/api/public/hooks/eval-tick': typeof ApiPublicHooksEvalTickRoute
  '/api/public/hooks/event-reactor-tick': typeof ApiPublicHooksEventReactorTickRoute
  '/api/public/hooks/indexer-tick': typeof ApiPublicHooksIndexerTickRoute
  '/api/public/hooks/memory-tick': typeof ApiPublicHooksMemoryTickRoute
  '/api/public/hooks/outcome-tick': typeof ApiPublicHooksOutcomeTickRoute
  '/api/public/hooks/researcher-tick': typeof ApiPublicHooksResearcherTickRoute
  '/api/public/hooks/resume-runs': typeof ApiPublicHooksResumeRunsRoute
  '/api/public/hooks/retention-tick': typeof ApiPublicHooksRetentionTickRoute
  '/api/public/hooks/scout-tick': typeof ApiPublicHooksScoutTickRoute
  '/api/public/hooks/sense-tick': typeof ApiPublicHooksSenseTickRoute
  '/api/public/hooks/steward-tick': typeof ApiPublicHooksStewardTickRoute
  '/api/public/hooks/trigger-tick': typeof ApiPublicHooksTriggerTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/a2a/message/send': typeof ApiPublicA2aMessageSendRoute
  '/api/public/a2a/message/stream': typeof ApiPublicA2aMessageStreamRoute
  '/api/public/connect/github/callback': typeof ApiPublicConnectGithubCallbackRoute
  '/api/public/a2a/agents/cadence/card': typeof ApiPublicA2aAgentsCadenceCardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/subprocessors'
    | '/trust'
    | '/admin'
    | '/agents'
    | '/analytics'
    | '/briefing'
    | '/budgets'
    | '/calendar'
    | '/changelog'
    | '/chat'
    | '/cockpit'
    | '/delegate'
    | '/discovery'
    | '/docs'
    | '/drift'
    | '/eval-health'
    | '/evals'
    | '/fleet'
    | '/govern'
    | '/governance'
    | '/guardrails'
    | '/impact'
    | '/inbox'
    | '/integrations'
    | '/knowledge'
    | '/learn'
    | '/meetings'
    | '/memory'
    | '/notifications'
    | '/observe'
    | '/onboarding'
    | '/opportunities'
    | '/outcome'
    | '/prds'
    | '/product'
    | '/prompts'
    | '/roadmap'
    | '/settings'
    | '/stakeholder'
    | '/swarm'
    | '/sync'
    | '/tasks'
    | '/today'
    | '/traces'
    | '/trust-ledger'
    | '/api/chat'
    | '/api/mcp'
    | '/checkout/return'
    | '/d/$slug'
    | '/join/$token'
    | '/p/$slug'
    | '/t/$slug'
    | '/admin/ai-costs'
    | '/admin/observability'
    | '/admin/people'
    | '/admin/platform'
    | '/admin/pricing'
    | '/admin/workspaces'
    | '/build/$missionId'
    | '/meetings/$id'
    | '/missions/$missionId'
    | '/prds/$id'
    | '/studio/$missionId'
    | '/traces/$traceId'
    | '/api/public/health'
    | '/api/public/ingest-signals'
    | '/api/stripe/webhook'
    | '/admin/'
    | '/build/'
    | '/missions/'
    | '/prds/'
    | '/studio/'
    | '/api/public/a2a/tasks'
    | '/api/public/hooks/admin-expiry-tick'
    | '/api/public/hooks/agent-tick'
    | '/api/public/hooks/approvals-tick'
    | '/api/public/hooks/cluster-tick'
    | '/api/public/hooks/credit-tick'
    | '/api/public/hooks/delegate-poll-tick'
    | '/api/public/hooks/derive-tick'
    | '/api/public/hooks/drift-tick'
    | '/api/public/hooks/eval-suite-tick'
    | '/api/public/hooks/eval-tick'
    | '/api/public/hooks/event-reactor-tick'
    | '/api/public/hooks/indexer-tick'
    | '/api/public/hooks/memory-tick'
    | '/api/public/hooks/outcome-tick'
    | '/api/public/hooks/researcher-tick'
    | '/api/public/hooks/resume-runs'
    | '/api/public/hooks/retention-tick'
    | '/api/public/hooks/scout-tick'
    | '/api/public/hooks/sense-tick'
    | '/api/public/hooks/steward-tick'
    | '/api/public/hooks/trigger-tick'
    | '/api/public/payments/webhook'
    | '/api/public/a2a/message/send'
    | '/api/public/a2a/message/stream'
    | '/api/public/connect/github/callback'
    | '/api/public/a2a/agents/cadence/card'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/subprocessors'
    | '/trust'
    | '/agents'
    | '/analytics'
    | '/briefing'
    | '/budgets'
    | '/calendar'
    | '/changelog'
    | '/chat'
    | '/cockpit'
    | '/delegate'
    | '/discovery'
    | '/docs'
    | '/drift'
    | '/eval-health'
    | '/evals'
    | '/fleet'
    | '/govern'
    | '/governance'
    | '/guardrails'
    | '/impact'
    | '/inbox'
    | '/integrations'
    | '/knowledge'
    | '/learn'
    | '/meetings'
    | '/memory'
    | '/notifications'
    | '/observe'
    | '/onboarding'
    | '/opportunities'
    | '/outcome'
    | '/product'
    | '/prompts'
    | '/roadmap'
    | '/settings'
    | '/stakeholder'
    | '/swarm'
    | '/sync'
    | '/tasks'
    | '/today'
    | '/traces'
    | '/trust-ledger'
    | '/api/chat'
    | '/api/mcp'
    | '/checkout/return'
    | '/d/$slug'
    | '/join/$token'
    | '/p/$slug'
    | '/t/$slug'
    | '/admin/ai-costs'
    | '/admin/observability'
    | '/admin/people'
    | '/admin/platform'
    | '/admin/pricing'
    | '/admin/workspaces'
    | '/build/$missionId'
    | '/meetings/$id'
    | '/missions/$missionId'
    | '/prds/$id'
    | '/studio/$missionId'
    | '/traces/$traceId'
    | '/api/public/health'
    | '/api/public/ingest-signals'
    | '/api/stripe/webhook'
    | '/admin'
    | '/build'
    | '/missions'
    | '/prds'
    | '/studio'
    | '/api/public/a2a/tasks'
    | '/api/public/hooks/admin-expiry-tick'
    | '/api/public/hooks/agent-tick'
    | '/api/public/hooks/approvals-tick'
    | '/api/public/hooks/cluster-tick'
    | '/api/public/hooks/credit-tick'
    | '/api/public/hooks/delegate-poll-tick'
    | '/api/public/hooks/derive-tick'
    | '/api/public/hooks/drift-tick'
    | '/api/public/hooks/eval-suite-tick'
    | '/api/public/hooks/eval-tick'
    | '/api/public/hooks/event-reactor-tick'
    | '/api/public/hooks/indexer-tick'
    | '/api/public/hooks/memory-tick'
    | '/api/public/hooks/outcome-tick'
    | '/api/public/hooks/researcher-tick'
    | '/api/public/hooks/resume-runs'
    | '/api/public/hooks/retention-tick'
    | '/api/public/hooks/scout-tick'
    | '/api/public/hooks/sense-tick'
    | '/api/public/hooks/steward-tick'
    | '/api/public/hooks/trigger-tick'
    | '/api/public/payments/webhook'
    | '/api/public/a2a/message/send'
    | '/api/public/a2a/message/stream'
    | '/api/public/connect/github/callback'
    | '/api/public/a2a/agents/cadence/card'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/subprocessors'
    | '/trust'
    | '/_authenticated/admin'
    | '/_authenticated/agents'
    | '/_authenticated/analytics'
    | '/_authenticated/briefing'
    | '/_authenticated/budgets'
    | '/_authenticated/calendar'
    | '/_authenticated/changelog'
    | '/_authenticated/chat'
    | '/_authenticated/cockpit'
    | '/_authenticated/delegate'
    | '/_authenticated/discovery'
    | '/_authenticated/docs'
    | '/_authenticated/drift'
    | '/_authenticated/eval-health'
    | '/_authenticated/evals'
    | '/_authenticated/fleet'
    | '/_authenticated/govern'
    | '/_authenticated/governance'
    | '/_authenticated/guardrails'
    | '/_authenticated/impact'
    | '/_authenticated/inbox'
    | '/_authenticated/integrations'
    | '/_authenticated/knowledge'
    | '/_authenticated/learn'
    | '/_authenticated/meetings'
    | '/_authenticated/memory'
    | '/_authenticated/notifications'
    | '/_authenticated/observe'
    | '/_authenticated/onboarding'
    | '/_authenticated/opportunities'
    | '/_authenticated/outcome'
    | '/_authenticated/prds'
    | '/_authenticated/product'
    | '/_authenticated/prompts'
    | '/_authenticated/roadmap'
    | '/_authenticated/settings'
    | '/_authenticated/stakeholder'
    | '/_authenticated/swarm'
    | '/_authenticated/sync'
    | '/_authenticated/tasks'
    | '/_authenticated/today'
    | '/_authenticated/traces'
    | '/_authenticated/trust-ledger'
    | '/api/chat'
    | '/api/mcp'
    | '/checkout/return'
    | '/d/$slug'
    | '/join/$token'
    | '/p/$slug'
    | '/t/$slug'
    | '/_authenticated/admin/ai-costs'
    | '/_authenticated/admin/observability'
    | '/_authenticated/admin/people'
    | '/_authenticated/admin/platform'
    | '/_authenticated/admin/pricing'
    | '/_authenticated/admin/workspaces'
    | '/_authenticated/build/$missionId'
    | '/_authenticated/meetings/$id'
    | '/_authenticated/missions/$missionId'
    | '/_authenticated/prds/$id'
    | '/_authenticated/studio/$missionId'
    | '/_authenticated/traces/$traceId'
    | '/api/public/health'
    | '/api/public/ingest-signals'
    | '/api/stripe/webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/build/'
    | '/_authenticated/missions/'
    | '/_authenticated/prds/'
    | '/_authenticated/studio/'
    | '/api/public/a2a/tasks'
    | '/api/public/hooks/admin-expiry-tick'
    | '/api/public/hooks/agent-tick'
    | '/api/public/hooks/approvals-tick'
    | '/api/public/hooks/cluster-tick'
    | '/api/public/hooks/credit-tick'
    | '/api/public/hooks/delegate-poll-tick'
    | '/api/public/hooks/derive-tick'
    | '/api/public/hooks/drift-tick'
    | '/api/public/hooks/eval-suite-tick'
    | '/api/public/hooks/eval-tick'
    | '/api/public/hooks/event-reactor-tick'
    | '/api/public/hooks/indexer-tick'
    | '/api/public/hooks/memory-tick'
    | '/api/public/hooks/outcome-tick'
    | '/api/public/hooks/researcher-tick'
    | '/api/public/hooks/resume-runs'
    | '/api/public/hooks/retention-tick'
    | '/api/public/hooks/scout-tick'
    | '/api/public/hooks/sense-tick'
    | '/api/public/hooks/steward-tick'
    | '/api/public/hooks/trigger-tick'
    | '/api/public/payments/webhook'
    | '/api/public/a2a/message/send'
    | '/api/public/a2a/message/stream'
    | '/api/public/connect/github/callback'
    | '/api/public/a2a/agents/cadence/card'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SubprocessorsRoute: typeof SubprocessorsRoute
  TrustRoute: typeof TrustRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiMcpRoute: typeof ApiMcpRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  DSlugRoute: typeof DSlugRoute
  JoinTokenRoute: typeof JoinTokenRoute
  PSlugRoute: typeof PSlugRoute
  TSlugRoute: typeof TSlugRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicIngestSignalsRoute: typeof ApiPublicIngestSignalsRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiPublicA2aTasksRoute: typeof ApiPublicA2aTasksRoute
  ApiPublicHooksAdminExpiryTickRoute: typeof ApiPublicHooksAdminExpiryTickRoute
  ApiPublicHooksAgentTickRoute: typeof ApiPublicHooksAgentTickRoute
  ApiPublicHooksApprovalsTickRoute: typeof ApiPublicHooksApprovalsTickRoute
  ApiPublicHooksClusterTickRoute: typeof ApiPublicHooksClusterTickRoute
  ApiPublicHooksCreditTickRoute: typeof ApiPublicHooksCreditTickRoute
  ApiPublicHooksDelegatePollTickRoute: typeof ApiPublicHooksDelegatePollTickRoute
  ApiPublicHooksDeriveTickRoute: typeof ApiPublicHooksDeriveTickRoute
  ApiPublicHooksDriftTickRoute: typeof ApiPublicHooksDriftTickRoute
  ApiPublicHooksEvalSuiteTickRoute: typeof ApiPublicHooksEvalSuiteTickRoute
  ApiPublicHooksEvalTickRoute: typeof ApiPublicHooksEvalTickRoute
  ApiPublicHooksEventReactorTickRoute: typeof ApiPublicHooksEventReactorTickRoute
  ApiPublicHooksIndexerTickRoute: typeof ApiPublicHooksIndexerTickRoute
  ApiPublicHooksMemoryTickRoute: typeof ApiPublicHooksMemoryTickRoute
  ApiPublicHooksOutcomeTickRoute: typeof ApiPublicHooksOutcomeTickRoute
  ApiPublicHooksResearcherTickRoute: typeof ApiPublicHooksResearcherTickRoute
  ApiPublicHooksResumeRunsRoute: typeof ApiPublicHooksResumeRunsRoute
  ApiPublicHooksRetentionTickRoute: typeof ApiPublicHooksRetentionTickRoute
  ApiPublicHooksScoutTickRoute: typeof ApiPublicHooksScoutTickRoute
  ApiPublicHooksSenseTickRoute: typeof ApiPublicHooksSenseTickRoute
  ApiPublicHooksStewardTickRoute: typeof ApiPublicHooksStewardTickRoute
  ApiPublicHooksTriggerTickRoute: typeof ApiPublicHooksTriggerTickRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicA2aMessageSendRoute: typeof ApiPublicA2aMessageSendRoute
  ApiPublicA2aMessageStreamRoute: typeof ApiPublicA2aMessageStreamRoute
  ApiPublicConnectGithubCallbackRoute: typeof ApiPublicConnectGithubCallbackRoute
  ApiPublicA2aAgentsCadenceCardRoute: typeof ApiPublicA2aAgentsCadenceCardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subprocessors': {
      id: '/subprocessors'
      path: '/subprocessors'
      fullPath: '/subprocessors'
      preLoaderRoute: typeof SubprocessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trust-ledger': {
      id: '/_authenticated/trust-ledger'
      path: '/trust-ledger'
      fullPath: '/trust-ledger'
      preLoaderRoute: typeof AuthenticatedTrustLedgerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/traces': {
      id: '/_authenticated/traces'
      path: '/traces'
      fullPath: '/traces'
      preLoaderRoute: typeof AuthenticatedTracesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sync': {
      id: '/_authenticated/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AuthenticatedSyncRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/swarm': {
      id: '/_authenticated/swarm'
      path: '/swarm'
      fullPath: '/swarm'
      preLoaderRoute: typeof AuthenticatedSwarmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stakeholder': {
      id: '/_authenticated/stakeholder'
      path: '/stakeholder'
      fullPath: '/stakeholder'
      preLoaderRoute: typeof AuthenticatedStakeholderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/product': {
      id: '/_authenticated/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AuthenticatedProductRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prds': {
      id: '/_authenticated/prds'
      path: '/prds'
      fullPath: '/prds'
      preLoaderRoute: typeof AuthenticatedPrdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outcome': {
      id: '/_authenticated/outcome'
      path: '/outcome'
      fullPath: '/outcome'
      preLoaderRoute: typeof AuthenticatedOutcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/observe': {
      id: '/_authenticated/observe'
      path: '/observe'
      fullPath: '/observe'
      preLoaderRoute: typeof AuthenticatedObserveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings': {
      id: '/_authenticated/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof AuthenticatedMeetingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learn': {
      id: '/_authenticated/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof AuthenticatedLearnRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge': {
      id: '/_authenticated/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof AuthenticatedKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impact': {
      id: '/_authenticated/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof AuthenticatedImpactRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guardrails': {
      id: '/_authenticated/guardrails'
      path: '/guardrails'
      fullPath: '/guardrails'
      preLoaderRoute: typeof AuthenticatedGuardrailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/govern': {
      id: '/_authenticated/govern'
      path: '/govern'
      fullPath: '/govern'
      preLoaderRoute: typeof AuthenticatedGovernRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/evals': {
      id: '/_authenticated/evals'
      path: '/evals'
      fullPath: '/evals'
      preLoaderRoute: typeof AuthenticatedEvalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eval-health': {
      id: '/_authenticated/eval-health'
      path: '/eval-health'
      fullPath: '/eval-health'
      preLoaderRoute: typeof AuthenticatedEvalHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drift': {
      id: '/_authenticated/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof AuthenticatedDriftRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discovery': {
      id: '/_authenticated/discovery'
      path: '/discovery'
      fullPath: '/discovery'
      preLoaderRoute: typeof AuthenticatedDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/delegate': {
      id: '/_authenticated/delegate'
      path: '/delegate'
      fullPath: '/delegate'
      preLoaderRoute: typeof AuthenticatedDelegateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cockpit': {
      id: '/_authenticated/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof AuthenticatedCockpitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/changelog': {
      id: '/_authenticated/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof AuthenticatedChangelogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budgets': {
      id: '/_authenticated/budgets'
      path: '/budgets'
      fullPath: '/budgets'
      preLoaderRoute: typeof AuthenticatedBudgetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/briefing': {
      id: '/_authenticated/briefing'
      path: '/briefing'
      fullPath: '/briefing'
      preLoaderRoute: typeof AuthenticatedBriefingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prds/': {
      id: '/_authenticated/prds/'
      path: '/'
      fullPath: '/prds/'
      preLoaderRoute: typeof AuthenticatedPrdsIndexRouteImport
      parentRoute: typeof AuthenticatedPrdsRoute
    }
    '/_authenticated/missions/': {
      id: '/_authenticated/missions/'
      path: '/missions'
      fullPath: '/missions/'
      preLoaderRoute: typeof AuthenticatedMissionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/build/': {
      id: '/_authenticated/build/'
      path: '/build'
      fullPath: '/build/'
      preLoaderRoute: typeof AuthenticatedBuildIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest-signals': {
      id: '/api/public/ingest-signals'
      path: '/api/public/ingest-signals'
      fullPath: '/api/public/ingest-signals'
      preLoaderRoute: typeof ApiPublicIngestSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/traces/$traceId': {
      id: '/_authenticated/traces/$traceId'
      path: '/$traceId'
      fullPath: '/traces/$traceId'
      preLoaderRoute: typeof AuthenticatedTracesTraceIdRouteImport
      parentRoute: typeof AuthenticatedTracesRoute
    }
    '/_authenticated/studio/$missionId': {
      id: '/_authenticated/studio/$missionId'
      path: '/studio/$missionId'
      fullPath: '/studio/$missionId'
      preLoaderRoute: typeof AuthenticatedStudioMissionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/prds/$id': {
      id: '/_authenticated/prds/$id'
      path: '/$id'
      fullPath: '/prds/$id'
      preLoaderRoute: typeof AuthenticatedPrdsIdRouteImport
      parentRoute: typeof AuthenticatedPrdsRoute
    }
    '/_authenticated/missions/$missionId': {
      id: '/_authenticated/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/missions/$missionId'
      preLoaderRoute: typeof AuthenticatedMissionsMissionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meetings/$id': {
      id: '/_authenticated/meetings/$id'
      path: '/$id'
      fullPath: '/meetings/$id'
      preLoaderRoute: typeof AuthenticatedMeetingsIdRouteImport
      parentRoute: typeof AuthenticatedMeetingsRoute
    }
    '/_authenticated/build/$missionId': {
      id: '/_authenticated/build/$missionId'
      path: '/build/$missionId'
      fullPath: '/build/$missionId'
      preLoaderRoute: typeof AuthenticatedBuildMissionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/workspaces': {
      id: '/_authenticated/admin/workspaces'
      path: '/workspaces'
      fullPath: '/admin/workspaces'
      preLoaderRoute: typeof AuthenticatedAdminWorkspacesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pricing': {
      id: '/_authenticated/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AuthenticatedAdminPricingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/platform': {
      id: '/_authenticated/admin/platform'
      path: '/platform'
      fullPath: '/admin/platform'
      preLoaderRoute: typeof AuthenticatedAdminPlatformRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/people': {
      id: '/_authenticated/admin/people'
      path: '/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AuthenticatedAdminPeopleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/observability': {
      id: '/_authenticated/admin/observability'
      path: '/observability'
      fullPath: '/admin/observability'
      preLoaderRoute: typeof AuthenticatedAdminObservabilityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-costs': {
      id: '/_authenticated/admin/ai-costs'
      path: '/ai-costs'
      fullPath: '/admin/ai-costs'
      preLoaderRoute: typeof AuthenticatedAdminAiCostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/trigger-tick': {
      id: '/api/public/hooks/trigger-tick'
      path: '/api/public/hooks/trigger-tick'
      fullPath: '/api/public/hooks/trigger-tick'
      preLoaderRoute: typeof ApiPublicHooksTriggerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/steward-tick': {
      id: '/api/public/hooks/steward-tick'
      path: '/api/public/hooks/steward-tick'
      fullPath: '/api/public/hooks/steward-tick'
      preLoaderRoute: typeof ApiPublicHooksStewardTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sense-tick': {
      id: '/api/public/hooks/sense-tick'
      path: '/api/public/hooks/sense-tick'
      fullPath: '/api/public/hooks/sense-tick'
      preLoaderRoute: typeof ApiPublicHooksSenseTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scout-tick': {
      id: '/api/public/hooks/scout-tick'
      path: '/api/public/hooks/scout-tick'
      fullPath: '/api/public/hooks/scout-tick'
      preLoaderRoute: typeof ApiPublicHooksScoutTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/retention-tick': {
      id: '/api/public/hooks/retention-tick'
      path: '/api/public/hooks/retention-tick'
      fullPath: '/api/public/hooks/retention-tick'
      preLoaderRoute: typeof ApiPublicHooksRetentionTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resume-runs': {
      id: '/api/public/hooks/resume-runs'
      path: '/api/public/hooks/resume-runs'
      fullPath: '/api/public/hooks/resume-runs'
      preLoaderRoute: typeof ApiPublicHooksResumeRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/researcher-tick': {
      id: '/api/public/hooks/researcher-tick'
      path: '/api/public/hooks/researcher-tick'
      fullPath: '/api/public/hooks/researcher-tick'
      preLoaderRoute: typeof ApiPublicHooksResearcherTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/outcome-tick': {
      id: '/api/public/hooks/outcome-tick'
      path: '/api/public/hooks/outcome-tick'
      fullPath: '/api/public/hooks/outcome-tick'
      preLoaderRoute: typeof ApiPublicHooksOutcomeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/memory-tick': {
      id: '/api/public/hooks/memory-tick'
      path: '/api/public/hooks/memory-tick'
      fullPath: '/api/public/hooks/memory-tick'
      preLoaderRoute: typeof ApiPublicHooksMemoryTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/indexer-tick': {
      id: '/api/public/hooks/indexer-tick'
      path: '/api/public/hooks/indexer-tick'
      fullPath: '/api/public/hooks/indexer-tick'
      preLoaderRoute: typeof ApiPublicHooksIndexerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/event-reactor-tick': {
      id: '/api/public/hooks/event-reactor-tick'
      path: '/api/public/hooks/event-reactor-tick'
      fullPath: '/api/public/hooks/event-reactor-tick'
      preLoaderRoute: typeof ApiPublicHooksEventReactorTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eval-tick': {
      id: '/api/public/hooks/eval-tick'
      path: '/api/public/hooks/eval-tick'
      fullPath: '/api/public/hooks/eval-tick'
      preLoaderRoute: typeof ApiPublicHooksEvalTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/eval-suite-tick': {
      id: '/api/public/hooks/eval-suite-tick'
      path: '/api/public/hooks/eval-suite-tick'
      fullPath: '/api/public/hooks/eval-suite-tick'
      preLoaderRoute: typeof ApiPublicHooksEvalSuiteTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/drift-tick': {
      id: '/api/public/hooks/drift-tick'
      path: '/api/public/hooks/drift-tick'
      fullPath: '/api/public/hooks/drift-tick'
      preLoaderRoute: typeof ApiPublicHooksDriftTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/derive-tick': {
      id: '/api/public/hooks/derive-tick'
      path: '/api/public/hooks/derive-tick'
      fullPath: '/api/public/hooks/derive-tick'
      preLoaderRoute: typeof ApiPublicHooksDeriveTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/delegate-poll-tick': {
      id: '/api/public/hooks/delegate-poll-tick'
      path: '/api/public/hooks/delegate-poll-tick'
      fullPath: '/api/public/hooks/delegate-poll-tick'
      preLoaderRoute: typeof ApiPublicHooksDelegatePollTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/credit-tick': {
      id: '/api/public/hooks/credit-tick'
      path: '/api/public/hooks/credit-tick'
      fullPath: '/api/public/hooks/credit-tick'
      preLoaderRoute: typeof ApiPublicHooksCreditTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cluster-tick': {
      id: '/api/public/hooks/cluster-tick'
      path: '/api/public/hooks/cluster-tick'
      fullPath: '/api/public/hooks/cluster-tick'
      preLoaderRoute: typeof ApiPublicHooksClusterTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/approvals-tick': {
      id: '/api/public/hooks/approvals-tick'
      path: '/api/public/hooks/approvals-tick'
      fullPath: '/api/public/hooks/approvals-tick'
      preLoaderRoute: typeof ApiPublicHooksApprovalsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agent-tick': {
      id: '/api/public/hooks/agent-tick'
      path: '/api/public/hooks/agent-tick'
      fullPath: '/api/public/hooks/agent-tick'
      preLoaderRoute: typeof ApiPublicHooksAgentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/admin-expiry-tick': {
      id: '/api/public/hooks/admin-expiry-tick'
      path: '/api/public/hooks/admin-expiry-tick'
      fullPath: '/api/public/hooks/admin-expiry-tick'
      preLoaderRoute: typeof ApiPublicHooksAdminExpiryTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/a2a/tasks': {
      id: '/api/public/a2a/tasks'
      path: '/api/public/a2a/tasks'
      fullPath: '/api/public/a2a/tasks'
      preLoaderRoute: typeof ApiPublicA2aTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/connect/github/callback': {
      id: '/api/public/connect/github/callback'
      path: '/api/public/connect/github/callback'
      fullPath: '/api/public/connect/github/callback'
      preLoaderRoute: typeof ApiPublicConnectGithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/a2a/message/stream': {
      id: '/api/public/a2a/message/stream'
      path: '/api/public/a2a/message/stream'
      fullPath: '/api/public/a2a/message/stream'
      preLoaderRoute: typeof ApiPublicA2aMessageStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/a2a/message/send': {
      id: '/api/public/a2a/message/send'
      path: '/api/public/a2a/message/send'
      fullPath: '/api/public/a2a/message/send'
      preLoaderRoute: typeof ApiPublicA2aMessageSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/a2a/agents/cadence/card': {
      id: '/api/public/a2a/agents/cadence/card'
      path: '/api/public/a2a/agents/cadence/card'
      fullPath: '/api/public/a2a/agents/cadence/card'
      preLoaderRoute: typeof ApiPublicA2aAgentsCadenceCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiCostsRoute: typeof AuthenticatedAdminAiCostsRoute
  AuthenticatedAdminObservabilityRoute: typeof AuthenticatedAdminObservabilityRoute
  AuthenticatedAdminPeopleRoute: typeof AuthenticatedAdminPeopleRoute
  AuthenticatedAdminPlatformRoute: typeof AuthenticatedAdminPlatformRoute
  AuthenticatedAdminPricingRoute: typeof AuthenticatedAdminPricingRoute
  AuthenticatedAdminWorkspacesRoute: typeof AuthenticatedAdminWorkspacesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiCostsRoute: AuthenticatedAdminAiCostsRoute,
  AuthenticatedAdminObservabilityRoute: AuthenticatedAdminObservabilityRoute,
  AuthenticatedAdminPeopleRoute: AuthenticatedAdminPeopleRoute,
  AuthenticatedAdminPlatformRoute: AuthenticatedAdminPlatformRoute,
  AuthenticatedAdminPricingRoute: AuthenticatedAdminPricingRoute,
  AuthenticatedAdminWorkspacesRoute: AuthenticatedAdminWorkspacesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMeetingsRouteChildren {
  AuthenticatedMeetingsIdRoute: typeof AuthenticatedMeetingsIdRoute
}

const AuthenticatedMeetingsRouteChildren: AuthenticatedMeetingsRouteChildren = {
  AuthenticatedMeetingsIdRoute: AuthenticatedMeetingsIdRoute,
}

const AuthenticatedMeetingsRouteWithChildren =
  AuthenticatedMeetingsRoute._addFileChildren(
    AuthenticatedMeetingsRouteChildren,
  )

interface AuthenticatedPrdsRouteChildren {
  AuthenticatedPrdsIdRoute: typeof AuthenticatedPrdsIdRoute
  AuthenticatedPrdsIndexRoute: typeof AuthenticatedPrdsIndexRoute
}

const AuthenticatedPrdsRouteChildren: AuthenticatedPrdsRouteChildren = {
  AuthenticatedPrdsIdRoute: AuthenticatedPrdsIdRoute,
  AuthenticatedPrdsIndexRoute: AuthenticatedPrdsIndexRoute,
}

const AuthenticatedPrdsRouteWithChildren =
  AuthenticatedPrdsRoute._addFileChildren(AuthenticatedPrdsRouteChildren)

interface AuthenticatedTracesRouteChildren {
  AuthenticatedTracesTraceIdRoute: typeof AuthenticatedTracesTraceIdRoute
}

const AuthenticatedTracesRouteChildren: AuthenticatedTracesRouteChildren = {
  AuthenticatedTracesTraceIdRoute: AuthenticatedTracesTraceIdRoute,
}

const AuthenticatedTracesRouteWithChildren =
  AuthenticatedTracesRoute._addFileChildren(AuthenticatedTracesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBriefingRoute: typeof AuthenticatedBriefingRoute
  AuthenticatedBudgetsRoute: typeof AuthenticatedBudgetsRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChangelogRoute: typeof AuthenticatedChangelogRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCockpitRoute: typeof AuthenticatedCockpitRoute
  AuthenticatedDelegateRoute: typeof AuthenticatedDelegateRoute
  AuthenticatedDiscoveryRoute: typeof AuthenticatedDiscoveryRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedDriftRoute: typeof AuthenticatedDriftRoute
  AuthenticatedEvalHealthRoute: typeof AuthenticatedEvalHealthRoute
  AuthenticatedEvalsRoute: typeof AuthenticatedEvalsRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedGovernRoute: typeof AuthenticatedGovernRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedGuardrailsRoute: typeof AuthenticatedGuardrailsRoute
  AuthenticatedImpactRoute: typeof AuthenticatedImpactRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedKnowledgeRoute: typeof AuthenticatedKnowledgeRoute
  AuthenticatedLearnRoute: typeof AuthenticatedLearnRoute
  AuthenticatedMeetingsRoute: typeof AuthenticatedMeetingsRouteWithChildren
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedObserveRoute: typeof AuthenticatedObserveRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedOutcomeRoute: typeof AuthenticatedOutcomeRoute
  AuthenticatedPrdsRoute: typeof AuthenticatedPrdsRouteWithChildren
  AuthenticatedProductRoute: typeof AuthenticatedProductRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStakeholderRoute: typeof AuthenticatedStakeholderRoute
  AuthenticatedSwarmRoute: typeof AuthenticatedSwarmRoute
  AuthenticatedSyncRoute: typeof AuthenticatedSyncRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedTracesRoute: typeof AuthenticatedTracesRouteWithChildren
  AuthenticatedTrustLedgerRoute: typeof AuthenticatedTrustLedgerRoute
  AuthenticatedBuildMissionIdRoute: typeof AuthenticatedBuildMissionIdRoute
  AuthenticatedMissionsMissionIdRoute: typeof AuthenticatedMissionsMissionIdRoute
  AuthenticatedStudioMissionIdRoute: typeof AuthenticatedStudioMissionIdRoute
  AuthenticatedBuildIndexRoute: typeof AuthenticatedBuildIndexRoute
  AuthenticatedMissionsIndexRoute: typeof AuthenticatedMissionsIndexRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBriefingRoute: AuthenticatedBriefingRoute,
  AuthenticatedBudgetsRoute: AuthenticatedBudgetsRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChangelogRoute: AuthenticatedChangelogRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCockpitRoute: AuthenticatedCockpitRoute,
  AuthenticatedDelegateRoute: AuthenticatedDelegateRoute,
  AuthenticatedDiscoveryRoute: AuthenticatedDiscoveryRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedDriftRoute: AuthenticatedDriftRoute,
  AuthenticatedEvalHealthRoute: AuthenticatedEvalHealthRoute,
  AuthenticatedEvalsRoute: AuthenticatedEvalsRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedGovernRoute: AuthenticatedGovernRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedGuardrailsRoute: AuthenticatedGuardrailsRoute,
  AuthenticatedImpactRoute: AuthenticatedImpactRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedKnowledgeRoute: AuthenticatedKnowledgeRoute,
  AuthenticatedLearnRoute: AuthenticatedLearnRoute,
  AuthenticatedMeetingsRoute: AuthenticatedMeetingsRouteWithChildren,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedObserveRoute: AuthenticatedObserveRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedOutcomeRoute: AuthenticatedOutcomeRoute,
  AuthenticatedPrdsRoute: AuthenticatedPrdsRouteWithChildren,
  AuthenticatedProductRoute: AuthenticatedProductRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStakeholderRoute: AuthenticatedStakeholderRoute,
  AuthenticatedSwarmRoute: AuthenticatedSwarmRoute,
  AuthenticatedSyncRoute: AuthenticatedSyncRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedTracesRoute: AuthenticatedTracesRouteWithChildren,
  AuthenticatedTrustLedgerRoute: AuthenticatedTrustLedgerRoute,
  AuthenticatedBuildMissionIdRoute: AuthenticatedBuildMissionIdRoute,
  AuthenticatedMissionsMissionIdRoute: AuthenticatedMissionsMissionIdRoute,
  AuthenticatedStudioMissionIdRoute: AuthenticatedStudioMissionIdRoute,
  AuthenticatedBuildIndexRoute: AuthenticatedBuildIndexRoute,
  AuthenticatedMissionsIndexRoute: AuthenticatedMissionsIndexRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SubprocessorsRoute: SubprocessorsRoute,
  TrustRoute: TrustRoute,
  ApiChatRoute: ApiChatRoute,
  ApiMcpRoute: ApiMcpRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  DSlugRoute: DSlugRoute,
  JoinTokenRoute: JoinTokenRoute,
  PSlugRoute: PSlugRoute,
  TSlugRoute: TSlugRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicIngestSignalsRoute: ApiPublicIngestSignalsRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiPublicA2aTasksRoute: ApiPublicA2aTasksRoute,
  ApiPublicHooksAdminExpiryTickRoute: ApiPublicHooksAdminExpiryTickRoute,
  ApiPublicHooksAgentTickRoute: ApiPublicHooksAgentTickRoute,
  ApiPublicHooksApprovalsTickRoute: ApiPublicHooksApprovalsTickRoute,
  ApiPublicHooksClusterTickRoute: ApiPublicHooksClusterTickRoute,
  ApiPublicHooksCreditTickRoute: ApiPublicHooksCreditTickRoute,
  ApiPublicHooksDelegatePollTickRoute: ApiPublicHooksDelegatePollTickRoute,
  ApiPublicHooksDeriveTickRoute: ApiPublicHooksDeriveTickRoute,
  ApiPublicHooksDriftTickRoute: ApiPublicHooksDriftTickRoute,
  ApiPublicHooksEvalSuiteTickRoute: ApiPublicHooksEvalSuiteTickRoute,
  ApiPublicHooksEvalTickRoute: ApiPublicHooksEvalTickRoute,
  ApiPublicHooksEventReactorTickRoute: ApiPublicHooksEventReactorTickRoute,
  ApiPublicHooksIndexerTickRoute: ApiPublicHooksIndexerTickRoute,
  ApiPublicHooksMemoryTickRoute: ApiPublicHooksMemoryTickRoute,
  ApiPublicHooksOutcomeTickRoute: ApiPublicHooksOutcomeTickRoute,
  ApiPublicHooksResearcherTickRoute: ApiPublicHooksResearcherTickRoute,
  ApiPublicHooksResumeRunsRoute: ApiPublicHooksResumeRunsRoute,
  ApiPublicHooksRetentionTickRoute: ApiPublicHooksRetentionTickRoute,
  ApiPublicHooksScoutTickRoute: ApiPublicHooksScoutTickRoute,
  ApiPublicHooksSenseTickRoute: ApiPublicHooksSenseTickRoute,
  ApiPublicHooksStewardTickRoute: ApiPublicHooksStewardTickRoute,
  ApiPublicHooksTriggerTickRoute: ApiPublicHooksTriggerTickRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicA2aMessageSendRoute: ApiPublicA2aMessageSendRoute,
  ApiPublicA2aMessageStreamRoute: ApiPublicA2aMessageStreamRoute,
  ApiPublicConnectGithubCallbackRoute: ApiPublicConnectGithubCallbackRoute,
  ApiPublicA2aAgentsCadenceCardRoute: ApiPublicA2aAgentsCadenceCardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
