-- CLOSE THE LAST DOOR INTO PER-USER TOOL SEEDING.
--
-- The previous migration made `agent_tools` an overrides table, cleared the
-- seeded rows and dropped the seeding trigger on `profiles`. That was not
-- enough, and checking rather than assuming is what caught it:
-- `handle_new_user` calls `seed_default_agent_tools(NEW.id)` and
-- `seed_studio_tools(NEW.id)` DIRECTLY, in its own body, not through the
-- trigger. So the seventeenth signup would still have been handed a full set of
-- rows, pinning that account to the tool policy of 2026-07 on the day it
-- arrived. Which is the exact failure the platform model exists to remove.
--
-- WHY THE FUNCTIONS ARE NEUTRALISED RATHER THAN THE CALLS REMOVED. The
-- migration that restored those calls records this about the trigger function:
-- "like the 2026-06-17 note, handle_new_user reverts when a Lovable sync
-- regenerates it from the schema model; re-apply after any such sync." Editing
-- `handle_new_user` therefore fixes it until the next sync regenerates the old
-- body and quietly reintroduces the seeding. Emptying the FUNCTIONS survives
-- that: however `handle_new_user` is rewritten, and whatever still calls these,
-- no rows appear.
--
-- They are kept as no-ops rather than dropped because `handle_new_user` and
-- several older migrations reference them by name, and a dropped function turns
-- a signup into an error and a migration replay into a failure. An empty
-- function is inert; a missing one is a break.
--
-- The agent ROSTER seeds are untouched and still run. `agents` genuinely is a
-- per-account table: it carries a user_id and is the target of about a dozen
-- foreign keys across the demo seed, so it cannot collapse into a code-side
-- registry the way tools could. `src/lib/spine/agent-roster-seed.test.ts` is the
-- gate that keeps that one honest instead.

create or replace function public.seed_default_agent_tools(_user_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  -- Intentionally empty. Tool availability is decided by TOOL_REGISTRY and
  -- src/lib/ai/tools/defaults.ts; `agent_tools` holds only per-account
  -- deviations. Seeding a row here would pin that account to today's policy.
  return;
end;
$$;

create or replace function public.seed_studio_tools(_user_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  return; -- see seed_default_agent_tools
end;
$$;

create or replace function public.seed_pm_lifecycle_tools(_user_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  return; -- see seed_default_agent_tools
end;
$$;

create or replace function public.seed_rf08_missing_agent_tools(_user_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  return; -- see seed_default_agent_tools
end;
$$;

create or replace function public.seed_seam2_ci_tools(_user_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  return; -- see seed_default_agent_tools
end;
$$;

create or replace function public.seed_station_agent_tools(_user_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  return; -- see seed_default_agent_tools
end;
$$;

create or replace function public.seed_agent_tools_for(_user_id uuid)
returns void language plpgsql security definer set search_path = public as $$
begin
  return; -- see seed_default_agent_tools
end;
$$;

comment on function public.seed_default_agent_tools(uuid) is
  'NO-OP since 2026-08-01. Tool availability is platform policy in code, not per-user rows. '
  'Kept callable because handle_new_user references it and is regenerated by Lovable syncs.';
