-- RF-01: outcome attribution breadth — provisional, confidence-tiered outcome
-- suggestions generated by chaining ship detection (outcome-tick), the
-- Historian draft (suggestOutcomeVerdict), SEN-05 PostHog usage deltas, and
-- the BYO-P3 changeset->PRD join. Mirrors prds.outcome's existing untyped-jsonb
-- convention (20260611161500) — plain ALTER TABLE, no new RLS policy needed
-- since prds RLS is already row-level and this is a same-row column.
ALTER TABLE public.prds ADD COLUMN IF NOT EXISTS outcome_suggestion jsonb;

COMMENT ON COLUMN public.prds.outcome_suggestion IS
  'RF-01: auto-drafted, confidence-tiered outcome suggestion ({verdict, summary, predicted, metric_label, metric_value, confidence, confidence_tier, basis, generated_at}). Only written by outcome-suggestion.server.ts, and only while prds.outcome is still null.';
