import { describe, it, expect } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

/**
 * THE GATE COULD NOT GO GREEN, SO NOBODY USED IT.
 *
 * WHAT WAS MEASURED, 2026-08-06. `bun run lint` reported 9,930 errors and exited
 * 1. Of those, 9,203 were inside `src/`, and 8,560 of THOSE came from one file:
 * `src/integrations/supabase/types.ts`, ~10k lines of Supabase types written by
 * Lovable's bot (`gpt-engineer-app[bot]`, regenerated wholesale -- see its git
 * history) and never prettier-formatted. A further ~725 came from
 * `test-results/`, Playwright's HTML report, whose minified vendor bundle
 * prettier reformats line by line. Both are gitignored.
 *
 * So 93% of the repo's lint baseline was machine-written code no person will
 * ever edit, and the documented gate could not pass on any machine that had run
 * a browser test. `.github/workflows/ci.yml` excludes the full lint from CI
 * citing "~4k legacy eslint findings in untouched files" -- a fair call against
 * the number it had, but the number was mostly this.
 *
 * After the ignores: 9,930 -> 1,121 errors, all in code humans wrote, which is a
 * figure someone can actually drive to zero.
 *
 * WHY THIS TEST EXISTS. The ignore list had not grown since it was written while
 * `.gitignore` learned six more entries, and nothing noticed for months because
 * the symptom (a red gate) was indistinguishable from the repo simply having
 * legacy findings. If an entry is dropped again the number silently returns to
 * five figures and the gate goes back to being ignored.
 *
 * NOTE FOR WHOEVER TOUCHES THIS: adding a path here is only legitimate when the
 * path is GENERATED. Excluding hand-written code to make a number look better is
 * the exact move `config-protection` exists to prevent, and this file is not a
 * licence for it.
 */

const CONFIG = readFileSync(join(import.meta.dir, "..", "..", "..", "eslint.config.js"), "utf8");
/* `.gitignore` is deliberately NOT read as text here any more: the ignore rules
   live across several files and git is the only thing that knows all of them.
   See the probe in "every ignored path is one git also refuses to store". */

/** The generated outputs that produced the five-figure baseline. */
const MUST_IGNORE = [
  "test-results", // Playwright HTML report: a minified vendor bundle
  "playwright-report",
  ".playwright-mcp",
  "src/integrations/supabase/types.ts", // 8,560 of the 9,203 src errors
  ".output",
  ".wrangler",
];

describe("eslint does not read generated output", () => {
  for (const path of MUST_IGNORE) {
    it(`ignores ${path}`, () => {
      expect({ path, ignored: CONFIG.includes(`"${path}"`) }).toEqual({ path, ignored: true });
    });
  }

  it("every ignored path is one git also refuses to store", () => {
    /**
     * THE RULE, made checkable: if git will not store it, eslint should not read
     * it. This is what separates "stop linting generated output" from "stop
     * linting the file that keeps failing" -- the second cannot pass this test,
     * because hand-written source is tracked.
     *
     * `dist` and `coverage` are conventional build outputs that this repo does
     * not currently produce, so they are absent from .gitignore and exempt.
     */
    const exempt = new Set([
      "dist",
      "coverage",
      ".vinxi",
      ".nitro",
      "playwright-cli",
      /**
       * THE ONE TRACKED PATH, AND THIS TEST CAUGHT ME OVERREACHING.
       *
       * `types.ts` IS committed -- TypeScript needs it at build time -- so the
       * gitignore rule above does not cover it and I should not pretend it does.
       * It qualifies on the other half of the reason: every change to it is
       * authored by `gpt-engineer-app[bot]` (Lovable), regenerated wholesale from
       * the Supabase schema. `git log -- src/integrations/supabase/types.ts`
       * shows commits titled "Changes" at 94 insertions / 104 deletions.
       *
       * "Tracked" and "written by a person" are different questions, and only
       * the second is the one that matters for whether a linter should read it.
       */
      "src/integrations/supabase/types.ts",
      /**
       * TWO MORE TRACKED PATHS, ON THE SAME HALF OF THE REASON (2026-09-09).
       *
       * Both are stored by git, so the gitignore rule does not cover them, and
       * both qualify the way `types.ts` does: not written by a person editing
       * application code.
       *
       * `.claude/workflows/**` are scripts for the Workflow tool, generated by
       * an agent from a prompt and run by a runtime that documents a top-level
       * `return`. Parsed as ES modules they report a syntax error for a file
       * that is correct where it runs, so the finding is about the parser's
       * assumption rather than the code.
       *
       * `docs/planning/archive/**` is archived by the folder's own name; the
       * repo's rule for archives is that they are history, not code.
       *
       * The test that follows still holds the line this list exists for: a path
       * gets in by being generated or archived, never by carrying findings
       * somebody would rather not fix.
       */
      ".claude/workflows/**",
      "docs/planning/archive/**",
    ]);
    // SCOPED TO THE ignores ARRAY. Scanning the whole file for quoted strings on
    // their own line also collects rule severities -- the first version of this
    // asserted that `"error"` was gitignored.
    const block = CONFIG.slice(
      CONFIG.indexOf("ignores: ["),
      CONFIG.indexOf("]", CONFIG.indexOf("ignores: [")),
    );
    const listed = [...block.matchAll(/"([^"]+)"/g)].map((m) => m[1]);
    expect(listed.length).toBeGreaterThan(5);
    /*
     * ── ASK GIT, DO NOT RE-IMPLEMENT GIT (2026-09-14) ────────────────────────
     *
     * This used to hand-parse the ROOT `.gitignore` and compare stems, and it
     * reported `.remember/tmp/**` as not ignored while git ignores it perfectly
     * well -- through a NESTED ignore file, `.remember/.gitignore`, whose single
     * line is `*`. Confirmed with `git check-ignore -v .remember/tmp/x`, which
     * names that file and that rule.
     *
     * So the config was right and the instrument was wrong, which made a real
     * guard fail on a real repo for a reason that had nothing to do with the
     * rule it protects. Nested ignore files, negations, `info/exclude` and the
     * global ignore file are all part of "will git store this", and none of them
     * is visible in one file's text.
     *
     * `git check-ignore` IS the question this test asks, so it is now the thing
     * being asked. `--no-index` keeps the answer about the ignore rules rather
     * than about whether the path happens to be tracked already, and a glob is
     * reduced to a concrete probe path because check-ignore matches paths, not
     * patterns. Exit code 0 means ignored, 1 means not; anything else is a
     * broken instrument and must not read as a pass.
     */
    for (const path of listed) {
      if (exempt.has(path)) continue;
      const stem = path.replace(/\/?\*\*?$/, "").replace(/\/$/, "");
      /*
       * BOTH THE PATH AND A PATH INSIDE IT, because a `dir/` pattern in
       * `.gitignore` matches DIRECTORIES ONLY: `check-ignore playwright-report`
       * answers "not ignored" while `playwright-report/anything` is ignored, and
       * the second is the question that matters. An eslint ignore entry exists to
       * stop the linter READING FILES at that location, so a file at that
       * location is the honest probe.
       */
      const root = join(import.meta.dir, "..", "..", "..");
      const ignored = [stem, `${stem}/.probe`].some((probe) => {
        const check = Bun.spawnSync(["git", "check-ignore", "--no-index", "-q", probe], {
          cwd: root,
        });
        if (check.exitCode > 1) {
          throw new Error(
            `git check-ignore could not answer for ${probe}: ${check.stderr.toString()}`,
          );
        }
        return check.exitCode === 0;
      });
      expect({ path, gitignored: ignored }).toEqual({ path, gitignored: true });
    }
  });

  it("no lint RULE was weakened to get the number down", () => {
    // The ignores are about WHICH FILES are read. If a future pass also starts
    // switching rules off, that is a different change wearing this one's
    // clothes. These three carried real findings in hand-written code.
    for (const rule of ["react-hooks", "react-refresh", "prettier"]) {
      expect({ rule, present: CONFIG.includes(rule) }).toEqual({ rule, present: true });
    }
    expect(CONFIG).not.toMatch(/"prettier\/prettier":\s*"off"/);
  });

  it("records that no-unused-vars is off, which PREDATES this change", () => {
    /**
     * NOT MINE, AND WORTH SOMEONE'S ATTENTION. `@typescript-eslint/no-unused-vars`
     * is set to "off" in this config and was before the ignores were touched. It
     * is the rule that catches a variable you captured and never read -- exactly
     * the defect shape found in `derive-tick.ts` on 2026-08-06, where a push
     * error was assigned to a variable nothing reported. A human found that; the
     * linter could not have.
     *
     * Asserted rather than fixed, because turning it back on is a separate change
     * with its own blast radius across a repo this size, and it belongs to
     * whoever owns the lint baseline. If someone turns it on, delete this test.
     */
    expect(CONFIG).toMatch(/"@typescript-eslint\/no-unused-vars":\s*"off"/);
  });
});
