/**
 * THE PUBLISHED ANSWER TO "DOES MERIDIAN HAVE X" MUST BE THE TREE'S ANSWER.
 *
 * `COMPONENTS.md` is generated by `scripts/meridian-exports.ts` and is the
 * file every lane is told to search before filing a `meridian-gap` request.
 * A generated file nobody is forced to regenerate is a snapshot, and its own
 * sibling doc says so in its first heading: *"Regenerate it, do not trust
 * it."* That instruction is an admission, not a safeguard.
 *
 * WHAT IT COST, 2026-09-10. The committed table was stale, and Lane 3 wrote
 * that "Meridian has a Dialog, an Action, a Picker and a Toggle, and NO text
 * input", kept a shadcn `Input`, and was about to record a gap in the file
 * for the next reader. `Input`, `Textarea` and `Field` are in `forms.tsx`.
 * 58 files import from that module; 37 import `Input` by name. Exactly two
 * files in the repo still used the shadcn one.
 *
 * THE SAME MISS, A THIRD TIME. `scripts/meridian-exports.ts` was written on
 * 2026-08-23 after two rulings in one evening asked a lane to BUILD `Block`
 * and `Pre`, both of which already existed in `surface-parts.tsx`. It has now
 * failed to prevent the thing it was written for, because being correct when
 * run is not the same as being run.
 *
 * The mechanism is always the directory listing: `ls meridian/` shows no
 * `Input.tsx`, so `Input` "does not exist". Nothing about that is careless —
 * it is the only cheap way to look, and it is wrong for every component whose
 * file is named for its group rather than for itself.
 */
import { describe, test, expect } from "bun:test";
import { readFileSync, mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const repoRoot = join(import.meta.dir, "..", "..", "..");
const published = join(repoRoot, "src", "components", "meridian", "COMPONENTS.md");

/** Re-render the table into a temp path, so the check never writes the repo. */
function regenerated(): string {
  const out = join(mkdtempSync(join(tmpdir(), "mrd-")), "COMPONENTS.md");
  const proc = Bun.spawnSync(["bun", join(repoRoot, "scripts", "meridian-exports.ts")], {
    cwd: repoRoot,
    env: { ...process.env, MERIDIAN_EXPORTS_OUT: out },
  });
  if (proc.exitCode !== 0) throw new Error(new TextDecoder().decode(proc.stderr));
  return readFileSync(out, "utf8");
}

describe("the published inventory is the tree", () => {
  test("COMPONENTS.md matches what the directory actually exports", () => {
    // Not a formatting check: the generator is deterministic, so any
    // difference at all is a component that landed, moved or left without the
    // published answer following it.
    expect(readFileSync(published, "utf8")).toBe(regenerated());
  });

  test("the components a lane is most likely to think are missing are listed", () => {
    // Each of these has been reported absent by someone reading the directory.
    // They are named here so this test says WHY it exists when it fails.
    const table = readFileSync(published, "utf8");
    for (const [symbol, file] of [
      ["Input", "forms.tsx"],
      ["Textarea", "forms.tsx"],
      ["Field", "forms.tsx"],
      ["Dialog", "Dialog.tsx"],
      ["Pre", "surface-parts.tsx"],
      // `Region`, NOT `Block`. The generated header named `Block` until
      // 2026-09-10, and there is no such export -- it was renamed and the
      // sentence outlived it. My own first version of this test asserted
      // `Block` for the same reason: I read the prose, not the table.
      ["Region", "surface-parts.tsx"],
    ] as const) {
      expect(table).toContain(`| \`${symbol}\` | \`${file}\` |`);
    }
  });
});
